### ISSUE TITLE
a mistake during lightdock

### ISSUE THREAD

**Issue by Fang-dream** [lightdock/lightdock#1]
Dear Brian Jimenez,
I used modeller homology modeling to get an antibody structure, and then I encountered an error when docking the antibody with a structure-known antigen using lightdock, I wanted to know what was wrong? Whether the antibody or antigen structure files need to be processed?
I used the default settings in the 2UUY example.
![Fig](https://user-images.githubusercontent.com/58978837/70995611-ed6e3100-210b-11ea-9a4c-309b2b2767d0.png)

[lightdock.zip](https://github.com/lightdock/lightdock/files/3973312/lightdock.zip)

**Comment by brianjimenez** [comment]
Hi @Fang-dream ,
`fastdfire` scorning function does not support hydrogen atoms nor other molecules different than standard amino-acids. Please, remove all the data generated by the setup and rerun it with the flags `--noh --noxt`, that should solve the problem.
Please let me know in case the problems persists, I'd glad to help you.
