### ISSUE TITLE
Lightdock in google colab

### ISSUE THREAD

**Issue by andresilvapimentel** [lightdock/lightdock#11]
Dear collaborators,
I have installed the lightdock in google colab. It is working fine, excluding the cluster analysis.
In the cluster analysis, I add the command:

!lgd_cluster_bsas.py swarm_37/gso_10.out

The swarm 37 was the one with the lowest interaction energy. And, I have generated 10 conformations that are located in the directory /swarm_37/
Unfortunately, after running the cluster analysis with the above command, the error message is:

/usr/local/lib/python3.6/dist-packages/Bio/SubsMat/__init__.py:131: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  BiopythonDeprecationWarning,
[lgd_cluster_bsas] INFO: Reading CA from lightdock_17.pdb
[lgd_cluster_bsas] ERROR: Error found reading a structure: lightdock_17.pdb is not a valid filename or a valid PDB identifier.
[lgd_cluster_bsas] ERROR: Did you generate the LightDock structures corresponding to this output file?

I do not understand why lightdock is trying to find the  file lightdock_17.pdb because I only generate 10 conformations.

Does anyone suggest any action to solve this issue?

Thanks in advance.
Andre Pimentel

**Comment by brianjimenez** [comment]
A couple of comments on `lgd_cluster_bsas.py`:
1) Script is expecting to be executed from inside the `swarm_M` directory where the `gso_N.out` file is located.
2) All structures from `gso_N.out` are expected to have been generated with `lgd_generate_conformations.py`.

So instead of only generating 10 conformations on that folder, please try again generating all of them and then running `lgd_cluster_bsas.py` inside the `swarm_M` directory.

**Comment by andresilvapimentel** [comment]
Dear Brian,
Thank you for your comments. Yes, I did exactly what your commented. I double checked it now to make sure I was doing exactly what you suggested.
I am not sure why It is looking for the lightdock_17.pdb file because I only generate 10 conformations.
Do you know why?

**Comment by andresilvapimentel** [comment]
Another issue...
I was trying to perform a flexible docking running the following command for setting up the system:

!lightdock3_setup.py -anm -anm_lig 10 -anm_rec 10 receptor.pdb ligand.pdb 100 80

Then, running the docking simulation with:
!lightdock3.py -s mj3h setup.json 10

The error message is:
[0] step 1
Process Tentacle-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/lightdock/parallel/kraken.py", line 20, in run
    task.run()
  File "/usr/local/lib/python3.6/dist-packages/lightdock/parallel/util.py", line 12, in run
    saving_path=self.saving_path, save_intermediary=True)
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/algorithm.py", line 38, in run
    self.swarm.update_luciferin()
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/swarm.py", line 21, in update_luciferin
    glowworm.compute_luciferin()
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/glowworm.py", line 49, in compute_luciferin
    self.scoring = sum([landscape_position.evaluate_objective_function() for landscape_position in self.landscape_positions])
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/glowworm.py", line 49, in <listcomp>
    self.scoring = sum([landscape_position.evaluate_objective_function() for landscape_position in self.landscape_positions])
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/searchspace/landscape.py", line 151, in evaluate_objective_function
    self.receptor_pose.coordinates += self.receptor.n_modes[i] * self.rec_extent[i]
TypeError: 'NoneType' object is not subscriptable
[1] step 1
Process Tentacle-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/lightdock/parallel/kraken.py", line 20, in run
    task.run()
  File "/usr/local/lib/python3.6/dist-packages/lightdock/parallel/util.py", line 12, in run
    saving_path=self.saving_path, save_intermediary=True)
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/algorithm.py", line 38, in run
    self.swarm.update_luciferin()
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/swarm.py", line 21, in update_luciferin
    glowworm.compute_luciferin()
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/glowworm.py", line 49, in compute_luciferin
    self.scoring = sum([landscape_position.evaluate_objective_function() for landscape_position in self.landscape_positions])
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/glowworm.py", line 49, in <listcomp>
    self.scoring = sum([landscape_position.evaluate_objective_function() for landscape_position in self.landscape_positions])
  File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/searchspace/landscape.py", line 151, in evaluate_objective_function
    self.receptor_pose.coordinates += self.receptor.n_modes[i] * self.rec_extent[i]
TypeError: 'NoneType' object is not subscriptable
[kraken] INFO: 100 ships destroyed
[lightdock] INFO: Finished.

Do you know what I am doing wrong?

**Comment by brianjimenez** [comment]
Sorry, `Mj3h` scoring function does not support ANM as it's not a full-atom scoring function.

> Another issue...
> I was trying to perform a flexible docking running the following command for setting up the system:
> 
> !lightdock3_setup.py -anm -anm_lig 10 -anm_rec 10 receptor.pdb ligand.pdb 100 80
> 
> Then, running the docking simulation with:
> !lightdock3.py -s mj3h setup.json 10
> 
> The error message is:
> [0] step 1
> Process Tentacle-1:
> Traceback (most recent call last):
> File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
> self.run()
> File "/usr/local/lib/python3.6/dist-packages/lightdock/parallel/kraken.py", line 20, in run
> task.run()
> File "/usr/local/lib/python3.6/dist-packages/lightdock/parallel/util.py", line 12, in run
> saving_path=self.saving_path, save_intermediary=True)
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/algorithm.py", line 38, in run
> self.swarm.update_luciferin()
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/swarm.py", line 21, in update_luciferin
> glowworm.compute_luciferin()
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/glowworm.py", line 49, in compute_luciferin
> self.scoring = sum([landscape_position.evaluate_objective_function() for landscape_position in self.landscape_positions])
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/glowworm.py", line 49, in
> self.scoring = sum([landscape_position.evaluate_objective_function() for landscape_position in self.landscape_positions])
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/searchspace/landscape.py", line 151, in evaluate_objective_function
> self.receptor_pose.coordinates += self.receptor.n_modes[i] * self.rec_extent[i]
> TypeError: 'NoneType' object is not subscriptable
> [1] step 1
> Process Tentacle-2:
> Traceback (most recent call last):
> File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
> self.run()
> File "/usr/local/lib/python3.6/dist-packages/lightdock/parallel/kraken.py", line 20, in run
> task.run()
> File "/usr/local/lib/python3.6/dist-packages/lightdock/parallel/util.py", line 12, in run
> saving_path=self.saving_path, save_intermediary=True)
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/algorithm.py", line 38, in run
> self.swarm.update_luciferin()
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/swarm.py", line 21, in update_luciferin
> glowworm.compute_luciferin()
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/glowworm.py", line 49, in compute_luciferin
> self.scoring = sum([landscape_position.evaluate_objective_function() for landscape_position in self.landscape_positions])
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/glowworm.py", line 49, in
> self.scoring = sum([landscape_position.evaluate_objective_function() for landscape_position in self.landscape_positions])
> File "/usr/local/lib/python3.6/dist-packages/lightdock/gso/searchspace/landscape.py", line 151, in evaluate_objective_function
> self.receptor_pose.coordinates += self.receptor.n_modes[i] * self.rec_extent[i]
> TypeError: 'NoneType' object is not subscriptable
> [kraken] INFO: 100 ships destroyed
> [lightdock] INFO: Finished.
> 
> Do you know what I am doing wrong?

**Comment by brianjimenez** [comment]
I've never tested LightDock from a notebook, I guess some path assumption might be wrong. Would you mind sharing this notebook together with the input PDB files? Then I would try to test it on Jupyter Notebook and Colab.

> Dear Brian,
> Thank you for your comments. Yes, I did exactly what your commented. I double checked it now to make sure I was doing exactly what you suggested.
> I am not sure why It is looking for the lightdock_17.pdb file because I only generate 10 conformations.
> Do you know why?

**Comment by brianjimenez** [comment]
Error message will be improved in #12

**Comment by andresilvapimentel** [comment]
can share it, sure. I am using the test example in the tutorial. It is pretty straightforward. I just turned my computer off and closed for the weekend.
If you want, you can just install lightdock using pip, and use the basic commands, very easy. It works fine, except the cluster analysis

**Comment by brianjimenez** [comment]
Implemented in version 0.9.0a2, tested on Google Colab: `!pip install lightdock==0.9.0a2`

https://colab.research.google.com/gist/brianjimenez/927f0749fbabf943e472f95d87bd425b/lightdock_101.ipynb

Please reopen issue if you experience any issue concerning `lgd_cluster_bsas.py`.

**Comment by andresilvapimentel** [comment]
Dear Brian,
I opened your colab notebook above and worked fine with the commands:
!lightdock3_setup.py 2UUY_rec.pdb 2UUY_lig.pdb -s 100 -g 80
!lightdock3.py setup.json 20 -s fastdfire -l 0
!lgd_generate_conformations.py 2UUY_rec.pdb 2UUY_lig.pdb swarm_0/gso_20.out 80
!lgd_cluster_bsas.py swarm_0/gso_20.out

Then, I tried to perform the same with my receptor and ligand using the following commands:
!lightdock3_setup.py rec.pdb lig.pdb -s 100 -g 80
!lightdock3.py -s mj3h setup.json 10 -l 0
!lgd_generate_conformations.py --setup setup.json rec.pdb lig.pdb swarm_38/gso_10.out 10
!lgd_cluster_bsas.py swarm_38/gso_10.out

The error message was:
[lgd_cluster_bsas] INFO: Reading CA from /content/swarm_11/lightdock_68.pdb
[lgd_cluster_bsas] ERROR: Clustering has failed. Please see error:
[lgd_cluster_bsas] ERROR: object of type 'PosixPath' has no len()

I repeated this for a couple systems to check if anything was wrong with files, but none worked for me showing up the same message.
I am not sure if the mj3h score function works with clustering. I used the mj3h score function with your notebook and worked fine.

Another comment... When I run !lightdock3_setup.py rec.pdb lig.pdb -s 100 -g 80

[pdb] WARNING: Possible problem: [SideChainError] Incomplete sidechain for residue ILE.5
[pdb] WARNING: Possible problem: [SideChainError] Incomplete sidechain for residue ILE.9

I am not sure if this can cause any issue. I hope you know what is going on.

**Comment by brianjimenez** [comment]
```
!lightdock3_setup.py rec.pdb lig.pdb -s 100 -g 80
!lightdock3.py -s mj3h setup.json 10 -l 0
!lgd_generate_conformations.py --setup setup.json rec.pdb lig.pdb swarm_38/gso_10.out 10
!lgd_cluster_bsas.py swarm_38/gso_10.out
```
Problem here is that you are only simulating swarm 0 (please note the `-l 0` flag which means only run for swarm 0).
Then, `lgd_generate_conformations.py --setup setup.json rec.pdb lig.pdb swarm_38/gso_10.out 10` is failing to generate the predicted structures since the swarm 38 is not the one simulated on previous step.
Final clustering fails because of the same reason.

About the warning, is just a way of flagging incomplete side chains, which might affect the quality of predictions if that residue is for example part of the interface.

**Comment by andresilvapimentel** [comment]
My first try was without -l 0 which It did not work it. Then, I tried with -l 0 and it did not work it as well.

**Comment by brianjimenez** [comment]
This is the correct pipeline according to your input:

```
!lightdock3_setup.py rec.pdb lig.pdb -s 100 -g 80
!lightdock3.py -s mj3h setup.json 10 -l 0
!lgd_generate_conformations.py --setup setup.json rec.pdb lig.pdb swarm_0/gso_10.out 80
!lgd_cluster_bsas.py swarm_0/gso_10.out
```

Please make sure `rec.pdb` and `lig.pdb` files are available in your Colab env.

**Comment by andresilvapimentel** [comment]
Yes, it is.

Em qui, 25 de fev de 2021 13:35, Brian Jimenez <notifications@github.com>
escreveu:

**Comment by andresilvapimentel** [comment]
It works fine now!!! Thanks.
