### ISSUE TITLE
Scoring functions supporting ANM

### ISSUE THREAD

**Issue by brianjimenez** [lightdock/lightdock#12]
To avoid confusion, raising a warning to the user when a scoring function incompatible with ANM is used with the `-anm` flag would be necessary.

**Comment by andresilvapimentel** [comment]
I can share it, sure. I am using the test example in the tutorial. It is pretty straightforward. I just turned my computer off and closed for the weekend.
If you want, you can just install lightdock using pip, and use the basic commands, very easy. It works fine, except the cluster analysis.

**Comment by brianjimenez** [comment]
Implemented in [0.9.0](https://github.com/lightdock/lightdock/tree/0.9.0) branch
