### ISSUE TITLE
`setup.py` depends on `numpy` but you may not have `numpy` preinstalled.

### ISSUE THREAD

**Issue by zacharyrs** [lightdock/lightdock#14]
**Describe the bug**
The `setup.py` file uses `numpy` but is also where `lightdock` defines it depends on `numpy`. 

**To Reproduce**
Simply run `pip install lightdock` on a fresh environment (i.e. without `numpy` installed).

**Expected behavior**
Should install `numpy` and run the related code after? 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04.2 LTS

**Comment by brianjimenez** [comment]
Hi @zacharyrs , thanks for reporting this issue. Indeed, this is a catch-22 situation since the package depends on a library is used to build at setup time (`numpy` and the rest of Cython and Python C code). I'm afraid there is nothing I can do to avoid this deadlock.

**Comment by zacharyrs** [comment]
Hi @brianjimenez - not sure if it's worth the effort (or the potential messiness) but there is an approach to get around this as shown [here](https://github.com/MDAnalysis/mdanalysis/blob/64840d5df32ecb73ceadcc022dc4b71738537404/package/setup.py#L180).

**Comment by brianjimenez** [comment]
Thanks @zacharyrs ! It looks like quite a smart way to delay numpy import until pip figures it out, definitely worth a try. Thanks for pointing out to this workaround!

**Comment by brianjimenez** [comment]
Build, tests and integration worked OK on Travis. Planned for release `0.9.1`
