### ISSUE TITLE
ERROR: [NotSupportedInScoringError] Residue A.SER.1 or atom HT1 not supported. DFIRE only supports standard aminoacids without hydrogens.

### ISSUE THREAD

**Issue by o5728492** [lightdock/lightdock#16]
# wenyanbo @ WendeMacBook-Pro in ~/Schrodinger/test4 [14:58:33] 
$ lightdock3_setup.py 6LU7_prep.pdb EM.pdb -s 20 -g 40 
[lightdock3_setup] INFO: Reading structure from 6LU7_prep.pdb PDB file...
[pdb] WARNING: Possible problem: [BackboneError] Incomplete backbone for residue GLN.306
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue 02J.1
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue PJE.5
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue 010.6
[lightdock3_setup] INFO: 4779 atoms, 312 residues read.
[lightdock3_setup] INFO: Reading structure from EM.pdb PDB file...
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue UNK.1
[lightdock3_setup] INFO: 172 atoms, 1 residues read.
[lightdock3_setup] INFO: Calculating reference points for receptor 6LU7_prep.pdb...
[lightdock3_setup] INFO: Reference points for receptor found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating reference points for ligand EM.pdb...
[lightdock3_setup] INFO: Reference points for ligand found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating starting positions...
[lightdock3_setup] INFO: Generated 20 positions files
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Preparing environment
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: LightDock setup OK

$ lightdock3.py setup.json 10

[lightdock] INFO: simulation parameters saved to lightdock.info.1
[lightdock3_setup] INFO: Reading structure from lightdock_6LU7_prep.pdb PDB file...
[pdb] WARNING: Possible problem: [BackboneError] Incomplete backbone for residue GLN.306
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue 02J.1
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue PJE.5
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue 010.6
[lightdock3_setup] INFO: 4779 atoms, 312 residues read.
[lightdock3_setup] INFO: Reading structure from lightdock_EM.pdb PDB file...
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue UNK.1
[lightdock3_setup] INFO: 172 atoms, 1 residues read.
[lightdock] INFO: Loading scoring function...
[lightdock] INFO: Using DFIRE scoring function
[lightdock] ERROR: Error found in selected scoring function:
[lightdock] ERROR: [NotSupportedInScoringError] Residue A.SER.1 or atom HT1 not supported. DFIRE only supports standard aminoacids without hydrogens.

**Comment by brianjimenez** [comment]
Hi @o5728492 , remove all hydrogens and HETATM from your input structures, DFIRE scoring function only supports standard residues

**Comment by lonngxiang** [comment]
> Hi @o5728492 , remove all hydrogens and HETATM from your input structures, DFIRE scoring function only supports standard residues. Also make sure there are no residues with missing backbone atoms if you enable ANM.

Defining HETATM residues is supported here; However, all HETATM needs to be deleted when errors are reported. Isn't this a conflict？
![image](https://user-images.githubusercontent.com/40717349/220507362-b28d5db9-1ae3-4bd8-be28-04f161eae636.png)

**Comment by alchemistcai** [comment]
[FAQs for lightdock](https://lightdock.org/tutorials/0.9.3/faq#31-dfire-fails-with-keyerror)

Lightdock supports some different scoring functions,the default DFIRE doesn't support HETATM restraints,others **might** support.

**Comment by JorgeRoel** [comment]
One thing is LightDock, the other thing is the scoring function. You can have HETATM entries in your PDB files and perform the setup without running into issues (nothing new here as you can see in the issue above) and even define those as residue restraints (the new addition in the release you are referring to). However, for the simulation all HETATM need to be parametrised within the scoring function of your choice. This last consideration is, however, up to the user. We can provide some guidelines if you wish.

**Comment by lonngxiang** [comment]
> 



> [FAQs for lightdock](https://lightdock.org/tutorials/0.9.3/faq#31-dfire-fails-with-keyerror)
> 
> Lightdock supports some different scoring functions,the default DFIRE doesn't support HETATM restraints,others **might** support.

What scoring functions LightDock has, and what others support？

**Comment by brianjimenez** [comment]
A quick list of all of them:

```
lightdock3.py --listscoring
Available scoring functions are:  tobi, sd, dfire, fastdfire, cpydock, template, vdw, pisa, ddna, dna, dfire2, mj3h, sipper
```

Each of them in the list above have an independent folder at: https://github.com/lightdock/lightdock/tree/master/lightdock/scoring

**Comment by lonngxiang** [comment]
> One thing is LightDock, the other thing is the scoring function. You can have HETATM entries in your PDB files and perform the setup without running into issues (nothing new here as you can see in the issue above) and even define those as residue restraints (the new addition in the release you are referring to). However, for the simulation all HETATM need to be parametrised within the scoring function of your choice. This last consideration is, however, up to the user. We can provide some guidelines if you wish.

Thank you. In addition, please confirm whether LightDock protein-protein docking is flexible or rigid？

**Comment by JorgeRoel** [comment]
Again, take the time to read our tutorials and publications since you might find useful insights to your queries. Why do we then take the time to write them? :) 

Questions != issues
