### ISSUE TITLE
Reference count error encountered in sipper.c

### ISSUE THREAD

**Issue by maharjun** [lightdock/lightdock#19]
This is an error that is particularly difficult to reproduce but there nonetheless. I will explain the error here and demonstrate the solution that solved the issue for my setup. This is a bug in version 0.9.1

The error pertains to the following line in sipper.c and its use of the `PyArray_AsCArray` function.

https://github.com/lightdock/lightdock/blob/f9e610f5f3ff4e298b430ca0b67e49807796ced9/lightdock/scoring/sipper/c/sipper.c#L57

In this call, we use the `descr` object to specify the type. However, in the source of the numpy API it is mentioned that `PyArray_AsCArray` steals the reference to the descr object (see the [source code here](https://github.com/numpy/numpy/blob/ba6cd71b14df1ea2694354ac9ce84e8f2d7aa65a/numpy/core/src/multiarray/multiarraymodule.c#L233)). This means that the same descr object should not be used in both calls to PyArray_AsCArray.

Otherwise I understandably get the following error. 
```
*** Reference count error detected: an attempt was made to deallocate the dtype 12 (d) ***
```

This does not actually halt the computation of the fitness and is in practise more of a warning. But a particularly annoying warning considering the number of fitness calculations performed.

The fix for this is simply to create another reference to the descr object to make the code effectively as follows

```c
        // descr = PyArray_DescrFromType(NPY_DOUBLE);

        tmp0 = PyObject_GetAttrString(receptor_coordinates, "coordinates");
        tmp1 = PyObject_GetAttrString(ligand_coordinates, "coordinates");

        rec_len = PySequence_Size(tmp0);
        lig_len = PySequence_Size(tmp1);

        dims[1] = 3;
        dims[0] = rec_len;
        descr = PyArray_DescrFromType(NPY_DOUBLE);
        PyArray_AsCArray((PyObject **)&tmp0, (void **)&rec_array, dims, 2, descr);

        dims[0] = lig_len;
        descr = PyArray_DescrFromType(NPY_DOUBLE);  // ref gets stolen by PyArray_AsCArray
        PyArray_AsCArray((PyObject **)&tmp1, (void **)&lig_array, dims, 2, descr);
```

**Comment by brianjimenez** [comment]
Hi @maharjun , thanks again for your feedback. I've added your suggested patch to branch [0.9.2](https://github.com/lightdock/lightdock/tree/0.9.2), including fixes for `vdw` and `sd` scoring functions. Please, let me know if it's working fine on your side.
