### ISSUE TITLE
help with multiple scorings

### ISSUE THREAD

**Issue by victorfica** [lightdock/lightdock#2]
Dear @brianjimenez ,
On the simulation step, im trying to combine 2 scoring functions, using a scoring.conf file as follow:
sipper 0.8
fastdfire 0.5

The problem is im getting the following errors:
![Captura de pantalla 2019-12-17 a las 18 42 49](https://user-images.githubusercontent.com/16581137/71037326-3e772880-20fe-11ea-98f0-c95921c832db.png)

edit: I found it also happens using sipper alone.

**Comment by brianjimenez** [comment]
Hi @victorfica,
`sipper` scoring function is not working properly in the last build, thanks for notifying the issue.

**Comment by brianjimenez** [comment]
Issue should be solved now. Please @victorfica , could you check the last version solves the problem for you? There is a new release in pypi as well.

**Comment by victorfica** [comment]
Hi @brianjimenez ,
Thank you, the last version is working good, thanks for the quickly response .
In my lab we are very interested on the capabilities of your project, so probably some other questions will arise.

**Comment by brianjimenez** [comment]
Thank you @victorfica  for your kind words and for helping us making better lightdock. Please, don't hesitate to write us with more questions, we will be happy to answer them and help you.
