### ISSUE TITLE
Why not support docking a ligand?

### ISSUE THREAD

**Issue by UnixJunkie** [lightdock/lightdock#22]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow to dock lead-like or drug-like molecules.

**Describe alternatives you've considered**
Not use lightdock?

**Additional context**
N/A

**Comment by JorgeRoel** [comment]
Hi @UnixJunkie,

There is no technical limitation not enable protein-ligand docking in LightDock. However, at the moment neither of us is employed to actively develop the software and thus, the time we have to invest on it is rather limited. One might need to implement a new force field/scoring function to account for the new chemical types and protein-ligand interactions and reimplement the way flexibility is inferred via ANM (+ thorough testing and validating). In the meantime, you might want to try HADDOCK: https://bianca.science.uu.nl/haddock2.4/ , for which there are several recent papers describing different protocols: (except you are interested in giving a try :) )

- https://pubs.acs.org/doi/10.1021/acs.jcim.1c00796
- https://link.springer.com/article/10.1007%2Fs10822-019-00244-6
- https://link.springer.com/article/10.1007%2Fs10822-018-0148-4

Cheers

**Comment by UnixJunkie** [comment]
Ok, good to know.
Some docking programs manage to reproduce the scoring function of autodock Vina;
like idock IIRC: https://github.com/UnixJunkie/idock.
I am not sure how they do this though.
