### ISSUE TITLE
Selection does not work on Mac

### ISSUE THREAD

**Issue by aupilot** [lightdock/lightdock#24]
**Describe the bug**
All sorts of selection aren't shown on the 3D view screen on Mac. Neither v1.3, nor the daily build. However, works fine on linux

**To Reproduce**
Open a pdb. Menu "Select" "Chain" "...". 

**Expected behavior**
similar to linux - the selected resedues shown on 3D image.

**Screenshots**

**Desktop (please complete the following information):**
 - Mac OS 12.1 (Intel)

**Additional context**

**Comment by JorgeRoel** [comment]
Hi @aupilot 

I guess you are writing about some sort of molecular visualisation software external to LightDock. Please do refer to their official communications channel for more information or other asking forums.

Best,
Jorge

**Comment by aupilot** [comment]
Sorry Jorge, I submitted to a wrong repo :) 
That was about ChineraX... So, Please delete my silly issue :)

**Comment by JorgeRoel** [comment]
No problem, and thanks for your kind words!
