### ISSUE TITLE
¿ Se puede utilizar LightDock para "protein - ligand docking" ?

### ISSUE THREAD

**Issue by tochu-cha** [lightdock/lightdock#28]
Buenas, señor Jiménez.

Yo intentaba unas simulaciones de "docking" entre proteins y ligands. Ejemplos de "Tutorials" (https://lightdock.org/tutorials/0.9.2/index.html) los pude hacer más o menos bien.

Sin embargo, al intentar unas simulaciónes, no las pude.

Por esta página japonesa (https://qiita.com/kuro3210/items/a78cf96605f8ddd954f7) , intenté "docking simulation" de entre 2gz7 sin d3f (ligand) y d3f con LightDock.

1. descargué 2gz7.pdb de PDB
2. Por PyMol  "remove solven" , elegí d3f , "remove sel" , y guardé file como "2gz7_sin_lig.pdb"
3. Otro, d3f.pdb lo también guardé
4a. Por LightDock , "lightdock3_setup.py 2gz7_sin_lig.pdb d3f.pdb  --noxt --noh --now -anm"
Y , LightDock me dijo "Error selecting backbone atoms (protein or nucleic)"

Así que 

4b. "lightdock3_setup.py -s 200 2gz7_sin_lig.pdb d3f.pdb  --noxt --noh --now"
5a. "lightdock3.py setup.json 100"
Y, LightDock me dijo
"[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue D3F.307"
y
"Residue A.D3F.307 or atom CL1 not supported. DFIRE only supports standard aminoacids without hydrogens.".

Así que
5b. "lightdock3.py -s mj3h setup.json 100"
6. Por este página japonesa (https://hira-labo.com/archives/348) , modifiqué "analysis.sh" como
../4G6M_rec.pdb ../4G6M_lig.pdb  => ../2gz7_sin_lig.pdb ../d3f.pdb
-c 8  => lo borré
y
### Filtering models by >40% of satisfied restraints ### 
lgd_filter_restraints.py --cutoff 5.0 --fnat 0.4 rank_by_scoring.list restraints.list A B > /dev/null 2> /dev/null;
=> lo borré

7.  ./analysis.sh

Sin embargo, después de calculacíon, en "rank_by_*.list" todo "scoring"s son 0.000.
También, al hacer simulación en "7bf6.pdb" y su ligand "u08.pdb" , scorings son 0.000.

¿ LightDock , no lo puedo utilizar para "protein - ligand (que se hice de solo única molécula) docking" ?

Y otros unos.
Intentaba similar proceso en "pyDock web" y "LightDock server" , pero ellos me dijeron "No atoms found. Please check it is a correct PDB file" , "No protein found in PDB " ...

¿ Yo intento hacer unos locuros ?

Si me responda, estoy contento.

Un saludo

**Comment by brianjimenez** [comment]
Hola @tochu-cha !

Gracias por tu interés en LightDock y por el esfuerzo de escribir en español :-)

LightDock no está preparado para protein-ligand docking, entendiendo ligand como small-ligand, cofactors, etc., aunque con un poco de _hacking_ sí que podría llegarse a hacer (aunque posiblemente para ello ya hay otros software mucho mejor preparados y probados para esa tarea).

En cualquier caso, si quieres explorar cómo hacer el docking de [2gz7](https://www.rcsb.org/3d-view/2GZ7), hay algunas consideraciones a tener en cuenta:

- LightDock utiliza ProDy para calcular ANM (backbone flexibility) y no está preparado para small-ligand: no debes utilizar el flag `-anm` (esto ya lo has hecho).
- `DFIRE` no admite química que no sea uno de los 20 animoácidos estándar, pero puedes utilizar otro force-field (scoring function).

En la carpeta [scoring](https://github.com/lightdock/lightdock/tree/master/lightdock/scoring) del código fuente de LightDock encontrarás la implementación de las diferentes scoring functions. Por flexibilidad y posibilidades, creo que podrías intentar modificar `cpydock`, que es la implementación de la función PyDock en LightDock. PyDock utiliza internamente el force-field de Amber94: [amber.py](https://github.com/lightdock/lightdock/blob/master/lightdock/scoring/cpydock/data/amber.py), [solvation.py](https://github.com/lightdock/lightdock/blob/master/lightdock/scoring/cpydock/data/solvation.py) y [vdw.py](https://github.com/lightdock/lightdock/blob/master/lightdock/scoring/cpydock/data/vdw.py). 

Si añades lo necesario en esos ficheros para que D3F quede parametrizado, LightDock podría llegar a leer las diferentes cargas y hacer la simulación de docking.

En cualquier caso, esto solo resolvería parcialmente uno de los problemas: se trataría de una simulación de docking bound ya que no contarías con flexibilidad en ninguna de las dos moleculas (no habría minimización en el espacio de torsión de D3F, etc.). Pero si estás decidido a experimentar y consigues hacer las modificaciones, estaremos encantados de añadir tu código al repositorio de LightDock.

Muchas gracias de nuevo, ありがとうございました、しつれいしました

**Comment by brianjimenez** [comment]
Otra opción podría ser añadir otra scoring function a LightDock, por ejemplo [DLIGAND2](https://github.com/sysu-yanglab/DLIGAND2).
