### ISSUE TITLE
Lightdock prody dependency Issue

### ISSUE THREAD

**Issue by MonkeyTroopr** [lightdock/lightdock#29]
Attempting to install Lightdock using pip, automatically installs the prody dependency. However, the newest version of prody (2.0.2) causes issues with Lightdock, specifically the generation of swarm starting positions.

using pip to install prody (2.0.1) resolves this issue. 

Ubuntu 20.04

**Comment by brianjimenez** [comment]
Thanks for the heads up @MonkeyTroopr . We will fix ProDy version to 2.0.1 in the next LightDock release, for the moment workaround is to install Prody before LightDock on that specific version as you're pointing up:

```
pip install prody==2.0.1 && pip install lightdock
```

Leaving this issue opened until next LightDock release or ProDy team fixes installation on their next release.

**Comment by brianjimenez** [comment]
Fixed in release https://github.com/lightdock/lightdock/releases/tag/0.9.2.post1
