### ISSUE TITLE
Try to dock AMP (adenosine monophosphate) to a ssDNA

### ISSUE THREAD

**Issue by taoliu032** [lightdock/lightdock#31]
Hello!

**Describe the bug**
I was trying to dock a small molecule (adenosine monophosphate, ie, [AMP](https://pubchem.ncbi.nlm.nih.gov/compound/Adenosine-monophosphate)) to a ssDNA molecule using LightDock/0.9.0 but I could not get any "gso_{}.out" or "lightdock_{}.pdb" files in each "swarm_{}" folder, as shown in the screenshot. Therefore no final docked structure.

In each  `cluster_lightdock.list` file, it says:
> [lgd_cluster_bsas] ERROR: Clustering has failed. Please see error:
> [lgd_cluster_bsas] ERROR: [Errno 2] No such file or directory: 'gso_500.out'

**Screenshots**
<img width="454" alt="image" src="https://user-images.githubusercontent.com/18231148/173153338-a75d48b1-6c58-47f0-870d-88e1e691d38f.png">

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Rocky Linux 8.5 (Green Obsidian)

**Additional context**
Please see the PDB files for ssDNA and AMP in the attached .zip file below.

Thank you very much!

[DNA_AMP.zip](https://github.com/lightdock/lightdock/files/8882360/DNA_AMP.zip)

**Comment by taoliu032** [comment]
Here is more output info from my runs: a zip file that contains the .out files from the 4 steps of running lightdock (setup, run, rank, and find structures of top scores).

[out_files.zip](https://github.com/lightdock/lightdock/files/8882701/out_files.zip)

In the `lightdock_step2_run.out`, there are error messages indicating AMP as a ligand cannot be recognized:
> ....
> [lightdock3_setup] INFO: Reading structure from lightdock_AMP_H.pdb PDB file...
> [pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue AMP.1
> [lightdock3_setup] INFO: 35 atoms, 1 residues read.
> [lightdock] INFO: Loading scoring function...
> [lightdock] INFO: Using DNA scoring function
> [lightdock] ERROR: Error found in selected scoring function:
> [lightdock] ERROR: [NotSupportedInScoringError] Residue B.AMP.1 or atom P not supported. DNA scoring only supports AMBER94 types.

Therefore, as shown in `lightdock_step3_rank.out`, no swarms exist to be processed:

> [lgd_rank] WARNING: Results swarm_0/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_1/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_2/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_3/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_4/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_5/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_6/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_7/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_8/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_9/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_10/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_11/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_12/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_13/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_14/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_15/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_16/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_17/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_18/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_19/gso_500.out not found, ignoring.
> [lgd_rank] WARNING: Results swarm_20/gso_500.out not found, ignoring.
> [lgd_rank] INFO: Number of swarms: 21
> [lgd_rank] INFO: Number of steps: 500
> [lgd_rank] INFO: Output files: gso_500.out
> [lgd_rank] INFO: Number of swarms processed: 0
> [lgd_rank] INFO: Done.

I think the issue is that AMBER94 FF cannot describe AMP so that the regular docking procedures cannot be successfully executed - as you (Brian) mentioned in the Slack channel. Hopefully, adding missing parameters can help resolve this issue 🙏🤞

**Comment by JorgeRoel** [comment]
Hi @taoliu032 ,

We've been looking into this and have parametrized AMP. Preliminary tests show that simulation finishes without issues and poses are correctly generated. However, we can not judge if the results make any sense at all or need further optimization. Moreover, the current clustering protocol might not be the most appropriate. In any case, would you mind giving a try replacing the "lightdock/scoring/dna/data/amber.py" by the attached one?

Looking forward
[amber.py.gz](https://github.com/lightdock/lightdock/files/8909028/amber.py.gz)

**Comment by taoliu032** [comment]
@JorgeRoel  Thank you tremendously!🤩 I will give it try soon!

**Comment by JorgeRoel** [comment]
@taoliu032 Did you have the chance to try it out? I will close the issue by now but feel reopen it if needed.
