### ISSUE TITLE
Test files missing

### ISSUE THREAD

**Issue by merkys** [lightdock/lightdock#34]
**Describe the bug**
I am running nose tests for lightdock v0.9.2. A lot of tests fail with `No such file or directory`, citing various nonexistent directories under `lightdock/test/bin/`, for example, `scratch_dfire_short` or `scratch_dfire2_restraints`.

**To Reproduce**
```bash
cd lightdock && nosetests3
```

**Expected behavior**
Tests pass.

**Desktop:**
 - OS: Debian
 - Version: Unstable

**Comment by brianjimenez** [comment]
Please, could you try again using `virtualenv` and the steps described in the [Travis CI configuration file](https://github.com/lightdock/lightdock/blob/master/.travis.yml)?

**Comment by merkys** [comment]
I followed your advice and got the same results. Mentioned directories are not in the source tarball, should they somehow be downloaded during build/test phase?

**Comment by brianjimenez** [comment]
Those directories are temporal ones for the tests, created on the fly, and removed after every test is executed. It looks to me as there is some problem creating those directories, maybe a permission issue? You may try to execute only one of the tests to see if there is any error in that particular one, for example (`venv` is my particular virtualenv created):

```bash
cd lightdock
source venv/bin/activate
cd lightdock/test/bin
nosetests test_setup.py
```

If I call `pip freeze` in my virtualenv, this is the output with Python 3.8.13 (some of the libs might not be required since I'm also developing new features):

```
addict==2.4.0
biopython==1.79
coverage==6.4.1
cycler==0.11.0
Cython==0.29.30
fonttools==4.34.4
freesasa==2.1.0
joblib==1.1.0
kiwisolver==1.4.3
-e git+ssh://git@github.com/lightdock/lightdock.git@9b88232c17f81e54ef951162889c88f7952476db#egg=lightdock
matplotlib==3.5.2
nose==1.3.7
numpy==1.22.4
open3d==0.15.1
packaging==21.3
pandas==1.4.3
Pillow==9.2.0
ProDy==2.0.1
pyparsing==3.0.9
pyquaternion==0.9.9
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
scikit-learn==1.1.1
scipy==1.8.1
six==1.16.0
threadpoolctl==3.1.0
tqdm==4.64.0
```

Hope it helps

**Comment by brianjimenez** [comment]
Also the Travis run & log, it might be useful to check the steps: https://app.travis-ci.com/github/lightdock/lightdock/builds/252043216

**Comment by merkys** [comment]
Thanks, I think I found the problem: `prody==2.2.0` has incompatibilities with lightdock v0.9.2 which cause messages with `No such file or directory` appear in the output. I was wrong to assume these files were missing from the distribution, they were simply not created due to failures, just like you said. Closing the issue, thanks for prompt help.

**Comment by brianjimenez** [comment]
Thank you @merkys , no problem!
