### ISSUE TITLE
Tutorials for lightdock 0.9.3 is needed.

### ISSUE THREAD

**Issue by alchemistcai** [lightdock/lightdock#37]
Hello there!

Lightdock has updated to 0.9.3 and added the new `-spr` parameter and rewrited the implementation of creating swarms.

However,the tutorials have not updated to 0.9.3 and the different result may confuse beginners.

Also,using restraints now makes `starting_points.py` ignoring the `-s` flag,while the help information of `lightdock3_setup` didn't say that,which may confuse beginners too.

**Comment by brianjimenez** [comment]
New release 0.9.3.post1 will be also covered.

**Comment by brianjimenez** [comment]
Tutorials have been updated to 0.9.3 & 0.9.3.post1 releases. Fixed old links pointing to 0.9.1.

**Comment by zhl10154** [comment]
thanks, guys
