### ISSUE TITLE
lightdock online: how to fill Active Residue Restraints? any example？

### ISSUE THREAD

**Issue by lonngxiang** [lightdock/lightdock#41]
![image](https://user-images.githubusercontent.com/40717349/207565319-1b0f3d4d-3f1f-40a5-a430-ee9fccba8ef4.png)

**Comment by JorgeRoel** [comment]
Hi @lonngxiang, 

You can see the way you need to define the restraints already in the box. B.1, B.2 ..., where B stands for chainID and the number for the residue number. 

Cheers
