### ISSUE TITLE
[lgd_cluster_bsas] ERROR: object of type 'PosixPath' has no len()?

### ISSUE THREAD

**Issue by lonngxiang** [lightdock/lightdock#42]
run error:
lgd_cluster_bsas.py swarm_0/gso_100.out  or lgd_cluster_bsas.py swarm_1/gso_100.out
 
![image](https://user-images.githubusercontent.com/40717349/208003242-6ad83fc2-d29e-42fd-b303-19829f385fde.png)

swarm_0 and swarm_1  have datas:
![image](https://user-images.githubusercontent.com/40717349/208003089-c74b34df-af0b-411b-9f0d-1c6bd3fd770c.png)

**Comment by JorgeRoel** [comment]
You must generate the models before clustering.

**Comment by JorgeRoel** [comment]
Why would you want to simulate 200 glowworms but then only consider the first 10? (not even the best 10). GSO will converge into a number of different energy minima, each of them represented by a number of poses. The purpose of clustering here is to select a representative for each of these minima, thus removing redundant solutions. Of course you can customize it by modifying the script at your own risk, though this is not recommended.

**Comment by lonngxiang** [comment]
> Why would you want to simulate 200 glowworms but then only consider the first 10? (not even the best 10). GSO will converge into a number of different energy minima, each of them represented by a number of poses. The purpose of clustering here is to select a representative for each of these minima, thus removing redundant solutions. Of course you can customize it by modifying the script at your own risk, though this is not recommended.

It may be that lightdock3_setup.py automatically generates 200 glowworms in setup.json by default, so follow-up lgd_generate_conformations.py must also be filled in 200, otherwise, there will be an error in subsequent clustering

**Comment by JorgeRoel** [comment]
If you want to simulate a different number of glowworms you must define it during setup. Simply run lightdock3_setup.py -h to get a taste of all available options. But again, it is not a clustering error, it is a concept error. This is the expected behavior.

**Comment by lonngxiang** [comment]
> 

Ok, thank you for your patience

**Comment by lonngxiang** [comment]
> If you want to simulate a different number of glowworms you must define it during setup. Simply run lightdock3_setup.py -h to get a taste of all available options. But again, it is not a clustering error, it is a concept error. This is the expected behavior.

Ok, thank you for your patience
