### ISSUE TITLE
what the datas meaning of  cluster.repr file？

### ISSUE THREAD

**Issue by lonngxiang** [lightdock/lightdock#43]
after run lgd_cluster_bsas.py gso_100.out，how to look at ranking and scoring？
![image](https://user-images.githubusercontent.com/40717349/208081592-c148b181-0f5a-4fca-a06f-a7259d2c89a3.png)

**Comment by alchemistcai** [comment]
Please follow the official [tutorials](https://lightdock.org/tutorials/0.9.2/restraints) before starting your personal project.

You can also consider following my [translation and demonstrations](https://space.bilibili.com/102528003/channel/seriesdetail?sid=1912805) for these tutorials in Ipython.

These tutorials haven't update to Release 0.9.3 right now and act different when setting up.You may use release 0.9.1~0.9.2 first.Tutorials for release 0.9.3 will update soon.

**Comment by brianjimenez** [comment]
Thank you @alchemistcai for helping @lonngxiang and pointing out to the tutorials. @lonngxiang please also consider joining the official LightDock Slack space, which should be a better forum for asking questions. Here it is the invitation link:

[https://join.slack.com/t/lightdock/shared_invite/zt-14ezmx2hv-Opr3OgN99~5OfSWeNmUl2A](https://join.slack.com/t/lightdock/shared_invite/zt-14ezmx2hv-Opr3OgN99~5OfSWeNmUl2A)

**Comment by lonngxiang** [comment]
> 

@brianjimenez  Thanks for your patience, 

> Please follow the official [tutorials](https://lightdock.org/tutorials/0.9.2/restraints) before starting your personal project.
> 
> You can also consider following my [translation and demonstrations](https://space.bilibili.com/102528003/channel/seriesdetail?sid=1912805) for these tutorials in Ipython.
> 
> These tutorials haven't update to Release 0.9.3 right now and act different when setting up.You may use release 0.9.1~0.9.2 first.Tutorials for release 0.9.3 will update soon.

tks，great video and translation

**Comment by lonngxiang** [comment]
> Thank you @alchemistcai for helping @lonngxiang and pointing out to the tutorials. @lonngxiang please also consider joining the official LightDock Slack space, which should be a better forum for asking questions. Here it is the invitation link:
> 
> https://join.slack.com/t/lightdock/shared_invite/zt-14ezmx2hv-Opr3OgN99~5OfSWeNmUl2A
> 
> And to quickly answer your question, the two relevant scripts to see the final ranking are `lgd_top.py` and `lgd_rank.py`. There is a complete example using restraints here: https://lightdock.org/tutorials/0.9.2/restraints#53-generating-rank-and-filtering
> 
> Hope it helps!

@brianjimenez  Thanks for your patience. Great job
