### ISSUE TITLE
dna.pdb file empty after running `reduce_to_amber.py` and subsequent error during simulation

### ISSUE THREAD

**Issue by mhyleung** [lightdock/lightdock#45]
Dear all

I have constructed a predicted protein structure and generated a dna structure from Pymol based on a sequence of interest, and was following the tutorial for protein-DNA prediction.

After using `reduce` to clear and add hydrogens, my `reduce_to_amber.py` resulted in an empty output file.

Nonetheless, following setting up lightdock using the `lightdock3_setup.py` command, I tried to use the hydrogen-filled original dna structure .pdb file to run the simulation. I was given the following error:

```
[lightdock] ERROR: [NotSupportedInScoringError] Residue A.HIS.282 or atom HE2 not supported. DNA scoring only supports AMBER94 types.
```

It appears that it is in fact the protein structure that is giving me a problem. How should I go about fixing this?

Thank you very much

Marc

**Comment by brianjimenez** [comment]
Hi @mhyleung ,
You may need to rename HIS to HID in the protein partner. Then, you can follow these steps:

```bash
reduce -Trim prot.pdb > prot_no_h.pdb;
reduce -BUILD prot_no_h.pdb > prot_h.pdb;

reduce -Trim dna.pdb > dna_no_h.pdb;
reduce -BUILD dna_no_h.pdb > dna_h.pdb;
python reduce_to_amber.py dna_h.pdb fixed_dna_h.pdb;
```

You can use this more updated version of the `reduce_to_amber.py` script:

```python
#!/usr/bin/env python3

import os
import argparse
from lightdock.scoring.dna.data.amber import atoms_per_residue
from lightdock.pdbutil.PDBIO import read_atom_line


def _format_atom_name(atom_name):
    """Format ATOM name with correct padding"""
    if len(atom_name) == 4:
        return atom_name
    else:
        return " %s" % atom_name


def write_atom_line(atom, output):
    """Writes a PDB file format line to output."""
    if atom.__class__.__name__ == "HetAtom":
        atom_type = "HETATM"
    else:
        atom_type = "ATOM  "
    line = "%6s%5d %-4s%-1s%3s%2s%4d%1s   %8.3f%8.3f%8.3f%6.2f%6.2f%12s\n" % (
        atom_type,
        atom.number,
        _format_atom_name(atom.name),
        atom.alternative,
        atom.residue_name,
        atom.chain_id,
        atom.residue_number,
        atom.residue_insertion,
        atom.x,
        atom.y,
        atom.z,
        atom.occupancy,
        atom.b_factor,
        atom.element,
    )
    output.write(line)


translation = {"H5'":"H5'1", "H5''":"H5'2", "H2'":"H2'1", "H2''":"H2'2", "OP1":"O1P", "OP2":"O2P"}


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("input_pdb_file")
    parser.add_argument("output_pdb_file")
    args = parser.parse_args()

    with open(args.input_pdb_file) as ih:
        with open(args.output_pdb_file, 'w') as oh:
            for line in ih:
                line = line.rstrip(os.linesep)
                if line.startswith("ATOM  "):
                    atom = read_atom_line(line)
                    if atom.residue_name not in atoms_per_residue:
                        print(f"[Warning] Not supported atom: {atom.residue_name}.{atom.name}")
                    else:
                        if atom.name not in atoms_per_residue[atom.residue_name]:
                            try:
                                atom.name = translation[atom.name]
                                write_atom_line(atom, oh)
                            except KeyError:
                                print(f"[Warning] Atom not found in mapping: {atom.residue_name}.{atom.name}")
                        else:
                            write_atom_line(atom, oh)

```

If after this "protocol" you're still having issues with some atom types, it might be the capping at the C or N-terminal. Try to remove those hydrogens, remove all LightDock generated files in that directory and try again.

Let us know if this fixes your issues, otherwise you may follow @alchemistcai comment and share the structure (if possible).

**Comment by mhyleung** [comment]
Thank you for the rapid response. Neither the new script nor changing the HIS residues to HID helped. The error now simply is  
```
[lightdock] ERROR: [NotSupportedInScoringError] Residue A.HIS.282 or atom HE2 not supported. DNA scoring only supports AMBER94 types.
```

I have tried it also on another protein/DNA match constructed based on a similar fashion, run the new script and tried. The same HIS error occurred. This time, I noticed that when I change the HIS to HID, the `reduce -BUILD` step gives me this in the middle of the output:

```
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
SKIPPED H( A 325 ARGHH21 ): A 325 ARG NH2  bonds- A 329 MET SD   (H bumps)
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
*WARNING*: Res "HID" not in HETATM Connection Database. Hydrogens not added.
```

In any case, I have uploaded this other publicly available protein/DNA match here. Thank you very much
[github_pdb.zip](https://github.com/lightdock/lightdock/files/10434231/github_pdb.zip)

Marc

**Comment by alchemistcai** [comment]
1. If you rename HIS to HID manually,do it after Reduce removing and adding Hs,not before.
2. Reduce will generate HID and HIE both but won't change atom name.Renaming HIS to HID and using Reduce will cause wrong protonation.

![his](https://user-images.githubusercontent.com/60164864/212888959-8dab530d-458c-4135-9386-d9b51a64d796.png)

3. I have a solution:if you have installed GROMACS,use `pdb2pqr30 --ff=AMBER --ffout=AMBER --with-ph=7.4 github_protein.pdb gpamber.pqr`,and export it to pdb by Pymol.It will generate correct atom type.
4. Are there other more elegant solutions?Ambertools?I haven't figure it out.Maybe some PDB tools are more friendly on Amber FFs.
5. This pdb file may be used for the simulation directly.Try to run with it.Good luck.
[github_pdb_pqr.zip](https://github.com/lightdock/lightdock/files/10434650/github_pdb_pqr.zip)

**Comment by alchemistcai** [comment]
[Preparing PDB files with pdb4amber](https://ambermd.org/tutorials/basic/tutorial9/index.php).

A much easier way to work with amberFF's PDB files.I haven't test yet.But I think it would help.

**Comment by alchemistcai** [comment]
[Preparing PDB files with pdb4amber](https://ambermd.org/tutorials/basic/tutorial9/index.php).

A much easier way to work with amberFF's PDB files.Powered by Ambertools.

`pdb4amber --reduce github_protein.pdb >gpambertools.pdb` will help.

Ambertools must use `--reduce` flag to add hydrogens first to change correct atom names.

Ambertool's output has very different protonation from gromacs.Like this:

[gpambertools.zip](https://github.com/lightdock/lightdock/files/10435129/gpambertools.zip)

I'm not sure which one works better on protonation,Gromacs or Reduce.

**Comment by JorgeRoel** [comment]
Thanks @alchemistcai. Let's be patient 👼

**Comment by brianjimenez** [comment]
Hi @mhyleung , those files prepared by @alchemistcai should work. Please also note than the dna.pdb file is using `HETATM` instead of `ATOM` in your provided files. Please rename those entries before running `reduce_to_amber.py` or `lightdock3_setup.py`.

**Comment by brianjimenez** [comment]
After several iterations, I note down here a couple of important points:

- `reduce_to_amber.py` only processes `ATOM` entries and not `HETATM` in PDB files. Since `ATOM` is r**eserved for standard residues or nucleotides**, this should be the expected behavior.
- It is important to deal with missing atoms in backbone structure, specially when enabling flexibility through ANM.
- `reduce` command and many other software for managing protonation may add **capping hydrogens** and other atoms, which could be not supported by default in the specific scoring function used in LightDock at the time. Simply remove them if you encounter issues at the setup or simulations steps (if in the simulation, remove them from the PDB files, clean all generated files by LightDock during setup and run again setup script).
- Empty chains are not supported by LightDock, indeed, **empty chains might be a bad practice** when dealing with PDB information.

I close down for the moment this issue, please feel free to reopen it if there are more questions or issues related to the topic.
