### ISSUE TITLE
Swarm number remains 400 after using residue restraints

### ISSUE THREAD

**Issue by zhl10154** [lightdock/lightdock#48]
Try to run on examples from https://lightdock.org/tutorials/0.9.3/restraints

After running below command, supose to have swarm numebr reduced to 55 or similar. Somehow, it remains 400.
`lightdock3_setup.py 4G6M_rec.pdb 4G6M_lig.pdb --noxt --noh --now -anm -rst restraints.list`

Need some guidences, plz!

![bfef1e2f7107977e754b84dc7d1ce11](https://user-images.githubusercontent.com/12390526/220601639-a91496e8-3958-4fba-ae55-17c3bf12b8d4.png)

**Comment by alchemistcai** [comment]
Check this issue #37 .Need to update the tutorial.

**Comment by brianjimenez** [comment]
Indeed, this is a problem with the tutorial, needs to be updated as @alchemistcai suggests.

**Comment by brianjimenez** [comment]
As a workaround, @zhl10154 please use `-spr 10` during setup to fix the maximum number of swarms per restraints to 10 and having a similar number of swarms compared to the tutorial.

**Comment by zhl10154** [comment]
> As a workaround, @zhl10154 please use `-spr 10` during setup to fix the maximum number of swarms per restraints to 10 and having a similar number of swarms compared to the tutorial.

Thanks, man. I tried `-spr 10`, swarm number reduced to 220, it still takes a lot of time to compute. Will you update code to make it self-adaptive？

**Comment by brianjimenez** [comment]
It is self-adaptive to the number of restraints and region to sample. If you wish to decrease the number, just tweak `-spr` according to your expectations. In case you want to reproduce the current tutorial, please reinstall lightdock at version **0.9.2**. If you want to speedup calculations, use the [Rust implementation of LightDock](https://github.com/lightdock/lightdock-rust).
