### ISSUE TITLE
Can't find implicit membrane model for PBP2a protein on Memdock. 

### ISSUE THREAD

**Issue by inquisithustler** [lightdock/lightdock#49]
Please suggest how to proceed with membrane docking for PBP2a  @,if it's membrane model isn't available in any database. @brianjimenez @JorgeRoel @mvidalpinol

**Comment by brianjimenez** [comment]
@inquisithustler for PBP2a you mean [this](https://www.uniprot.org/uniprotkb/Q8DNB6/entry)?

**Comment by JorgeRoel** [comment]
Hi @inquisithustler . You can make use of the information available at UNIPROT (https://www.uniprot.org/uniprotkb/Q8DNB6/entry)- At UNIPROT you can see that the transmembrane domain spans across residues 57 to 77 (IILILGLSAGLLVGIYLFAVA). Depending whether your ligand binds on the Cytoplasm or on the Extracellular portion you can want to select ILE.57 or ALA.77 and our Membrane Builder utility (https://server.lightdock.org/membranator) to build an approximated layer ready-to-use for LightDock. Please give it a try let us know your thoughts

**Comment by brianjimenez** [comment]
Please @inquisithustler see @JorgeRoel 's answer and apply it to [Q93IC2](https://github.com/lightdock/lightdock/issues/url), there are crystals on the PDB ready to use.

**Comment by inquisithustler** [comment]
Yes @brianjimenez I looked into it and yes it worked for me. Thanks a lot @JorgeRoel.

**Comment by brianjimenez** [comment]
Awesome! I am closing this ticket for now, but please do ask any question you may have on our [Slack workspace](https://join.slack.com/t/lightdock/shared_invite/zt-14ezmx2hv-Opr3OgN99~5OfSWeNmUl2A).
