### ISSUE TITLE
Issues when docking

### ISSUE THREAD

**Issue by SciKidSirish** [lightdock/lightdock#52]
Hello, I am docking a Gastrin protein to the Cholecystokinin receptor.  When I do this, I get the following error:
```
[NormalModesCalculationError] Atoms differ: CB 99.255 109.616 129.421 - Atom N (index 3890)
```
How do I fix this?

Do you need the proteins' .pdb files?

**Comment by brianjimenez** [comment]
Issue has been answered on Slack, but for future questions:

> Problem comes from the input PDB structures, some residues might have some missing atoms for backbone or sidechain and ProDy (the library in charge of calculating flexibility via ANM) needs PDB complete structures. If you try removing `-anm` you would see that the docking moves on without issues.
To fix the problem, you will need to remove those partial residues or rebuild them. If you go for the second option, I recommend you to use [pdbfixer](https://github.com/openmm/pdbfixer) which is straightforward to install and use.
