### ISSUE TITLE
TOBI scoring function fails to replicate results with CCharPPI server

### ISSUE THREAD

**Issue by slemal-doc** [lightdock/lightdock#55]
Hi LightDock devs! I have been trying out some of the LightDock scoring function implementation throught the lgd_calculate_scoring.py script. I focused mainly on the PISA and TOBI scoring functions. To test them, I haver used the following benchmark set for Ab-Ag docking/binding, from Ref. Structure 29, 606–621, 2021. I compared values obtained from lgd_calculate_scoring.py and the CCharPPI webserver (https://life.bsc.es/pid/ccharppi), comparing 

- PISA (LightDock) vs AP_PISA (CCharPPI)
- TOBI (LightDock) vs AP_T2 (CCharPPI)

Here are the results 
![Screenshot 2023-05-08 at 09 22 39](https://user-images.githubusercontent.com/60929815/236795789-f725e132-bf69-4f40-8485-9aaf93a99eea.png)
![Screenshot 2023-05-08 at 09 22 47](https://user-images.githubusercontent.com/60929815/236795833-4fb59e3d-6fb6-44f5-8525-53584c6464d8.png)

It seems that PISA values are well reproduced, but not TOBI. I have not done the test for the other scoring functions, but it may be relevant to check them together with the authors of CCharPPI. Thank you very much!

**Comment by brianjimenez** [comment]
Please @slemal-doc could you test again if 0.9.4 fixes the difference in TOBI results as compared to CCharPPI?

**Comment by alchemistcai** [comment]
> Tobi, D. Designing coarse grained-and atom based-potentials for protein-protein docking. BMC Struct Biol 10, 40 (2010). https://doi.org/10.1186/1472-6807-10-40

It seems that lightdock implements TOBI's 2-step sidechain-based potentials(SDPs-II) instead of 2-step atomic-based potentials(ADPs-II) .





According to the paper above,ADPs-II performs more stable than SDPs-II.
According to CCharPPI's documents,AP-T2 seems to be ADPs-II.AP-T1 and AP-T2 are both classified as atomic potentials.I am not sure AP-T1 is whether ADPs-I or SDPs-II.





Anyway,lightdock's TOBI implementation is different with AP-T2.Maybe AP-T1's result fits better.

I haven't find semantic errors in tobi/driver.py.




---- Replied Message ----
| From | Brian ***@***.***> |
| Date | 08/08/2023 17:39 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [lightdock/lightdock] TOBI scoring function fails to replicate results with CCharPPI server (Issue #55) |

Please @slemal-doc could you test again if 0.9.4 fixes the difference in TOBI results as compared to CCharPPI?

**Comment by alchemistcai** [comment]
In the paper:

> In the side chain basedmodels the following steps were used: r1 ≤ 4.5 and 4.5 <r2 ≤6 Å for B-B, r1 ≤ 5.5 and 5.5 <r2 ≤7 Å for B-S, and r1 ≤ 6.5 and 6.5 <r2 ≤8.0 Å for S-S interactions to get a set of 253 × 2 = 506 parameters. In the atom-based models the following steps were used: r1 ≤ 4 and 4<r2≤6 Å to get a set of 171 × 2 = 342 parameters.

In lightdock's tobi/driver.py:

```py
if d <= 8.0:
    if rec_tobi >= 20 and lig_tobi >= 20:
        # Small distance, backbone-backbone
        if d <= 4.5:
            energy += self.potential.tobi_sc_1[rec_tobi][lig_tobi]
        else:
            if d <= 6.0:
                energy += self.potential.tobi_sc_2[rec_tobi][lig_tobi]
    else:
        # Medium distance, backbone-sidechain
        if rec_tobi >= 20 or lig_tobi >= 20:
            if d <= 5.5:
                energy += self.potential.tobi_sc_1[rec_tobi][lig_tobi]
            else:
                if d <= 7.0:
                    energy += self.potential.tobi_sc_2[rec_tobi][
                        lig_tobi
                    ]
        else:
            # Large distance, sidechain-sidechain
            if d <= 6.5:
                energy += self.potential.tobi_sc_1[rec_tobi][lig_tobi]
            else:
                if d <= 8.0:
                    energy += self.potential.tobi_sc_2[rec_tobi][
                        lig_tobi
                    ]
```

In CCharPPI's document:

- AP _T1. The first atomic two - step potential
described in BMC Struct . Biol .10:40(2010).
- AP _T2. The second atomic two - step potential described in BMC Struct . Biol.10:40(2010)

The images didn't show correctly.Refer to  this.



---- Replied Message ----
| From | Sébastien ***@***.***> |
| Date | 05/08/2023 18:03 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [lightdock/lightdock] TOBI scoring function fails to replicate results with CCharPPI server (Issue #55) |

Hi LightDock devs! I have been trying out some of the LightDock scoring function implementation throught the lgd_calculate_scoring.py script. I focused mainly on the PISA and TOBI scoring functions. To test them, I haver used the following benchmark set for Ab-Ag docking/binding, from Ref. Structure 29, 606–621, 2021. I compared values obtained from lgd_calculate_scoring.py and the CCharPPI webserver (https://life.bsc.es/pid/ccharppi), comparing

PISA (LightDock) vs AP_PISA (CCharPPI)
TOBI (LightDock) vs AP_T2 (CCharPPI)

Here are the results



It seems that PISA values are well reproduced, but not TOBI. I have not done the test for the other scoring functions, but it may be relevant to check them together with the authors of CCharPPI. Thank you very much!

**Comment by alchemistcai** [comment]
In the paper:

> In the side chain basedmodels the following steps were used: r1 ≤ 4.5 and 4.5 <r2 ≤6 Å for B-B, r1 ≤ 5.5 and 5.5 <r2 ≤7 Å for B-S, and r1 ≤ 6.5 and 6.5 <r2 ≤8.0 Å for S-S interactions to get a set of 253 × 2 = 506 parameters. In the atom-based models the following steps were used: r1 ≤ 4 and 4<r2≤6 Å to get a set of 171 × 2 = 342 parameters.

In lightdock's tobi/driver.py:

```py
if d <= 8.0:
    if rec_tobi >= 20 and lig_tobi >= 20:
        # Small distance, backbone-backbone
        if d <= 4.5:
            energy += self.potential.tobi_sc_1[rec_tobi][lig_tobi]
        else:
            if d <= 6.0:
                energy += self.potential.tobi_sc_2[rec_tobi][lig_tobi]
    else:
        # Medium distance, backbone-sidechain
        if rec_tobi >= 20 or lig_tobi >= 20:
            if d <= 5.5:
                energy += self.potential.tobi_sc_1[rec_tobi][lig_tobi]
            else:
                if d <= 7.0:
                    energy += self.potential.tobi_sc_2[rec_tobi][
                        lig_tobi
                    ]
        else:
            # Large distance, sidechain-sidechain
            if d <= 6.5:
                energy += self.potential.tobi_sc_1[rec_tobi][lig_tobi]
            else:
                if d <= 8.0:
                    energy += self.potential.tobi_sc_2[rec_tobi][
                        lig_tobi
                    ]
```

In CCharPPI's document:

- AP _T1. The first atomic two - step potential described in BMC Struct . Biol .10:40(2010).
- AP _T2. The second atomic two - step potential described in BMC Struct . Biol.10:40(2010)

The images didn't show correctly.Refer to  this.

**Comment by slemal-doc** [comment]
Hi all,

I've tried re-computing the TOBI score with LightDock 0.9.4 and comparing to AP_T1 and AP_T2 from CCharPPI. These are the following results (on the same set as provided in the Reference mentioned above): 
<img width="650" alt="Screenshot 2023-08-10 at 14 02 22" src="https://github.com/lightdock/lightdock/assets/60929815/0c4c565f-6ac6-497a-8a6c-0b510ecd0d52">

**Comment by brianjimenez** [comment]
Hi, thanks for the feedback. I don't have access anymore to the code on the CCharPPI server, but I've contacted the team in charge of maintaining it to share the code and see if there is any difference.

**Comment by brianjimenez** [comment]
I've split former `tobi` scoring function into `tobibahar` and `tobisc` in commit a5a05d5717c3ae2929ed4517241a25839be57fc5, from the upcoming `1.0.0` version.

* `tobibahar` is the potential described in:
Tobi, D. and Bahar, I. (2006), Optimal design of protein docking potentials: Efficiency and limitations.
Proteins, 62: 970-981. https://doi.org/10.1002/prot.20859

* `tobisc` is the side chain-based docking potentials (SDPs), step 1 & 2 as described in:
Tobi, D. Designing coarse grained-and atom based-potentials for protein-protein docking.
BMC Struct Biol 10, 40 (2010). https://doi.org/10.1186/1472-6807-10-40

I attach here the current code running at CCharPPI which is calculating all potentials (`get_pots.py`), including ADPs-I and ADPs-II: [tobi.tgz](https://github.com/lightdock/lightdock/files/12431542/tobi.tgz)

Hope it helps, @slemal-doc
