### ISSUE TITLE
Error encountered with DNA scoring function in lightdock3.py for DNA-DNA docking

### ISSUE THREAD

**Issue by MarielEsquivel98** [lightdock/lightdock#56]
When using the DNA scoring function in lightdock3.py, an error occurs related to unsupported residues or atoms.
Steps to reproduce the behavior: Run the command !lightdock3.py setup.json 100 -c 1 -s dna -l 60. Observe the error message and traceback.
Expected behavior. I expected the DNA scoring function to handle the residues and atoms properly and perform the docking simulation without errors.
Screenshots
**!lightdock3.py setup.json 100 -c 1 -sdfire -l 60**
[lightdock] INFO: simulation parameters saved to lightdock.info.3
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Reading structure from lightdock_AptN1V3_4C100_20_Own.pdb PDB file...
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.2
[lightdock3_setup] INFO: 525 atoms, 24 residues read.
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Reading structure from lightdock_Argus_target.pdb PDB file...
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.6
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.8
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.13
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.14
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.17
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.19
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.20
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue T.21
[lightdock3_setup] INFO: 517 atoms, 24 residues read.
[lightdock] INFO: Loading scoring function...
[lightdock] INFO: Using DNA scoring function
[lightdock] ERROR: Error found in selected scoring function:
[lightdock] ERROR: [NotSupportedInScoringError] Residue A.C.1 or atom O5* not supported. DNA scoring only supports AMBER94 types. 

Desktop:
OS: Windows 10
Python version: Python 3.8.5
lightdock3.py version: I'm using Google Colab

Additional context
I'm running the lightdock3.py script with the following command: !lightdock3.py setup.json 100 -c 1 -s dna -l 60 on a Linux machine (Ubuntu 20.04) with Python 3.10.0. The input PDB files used are lightdock_AptN1V3_4C100_20_Own.pdb and lightdock_Argus_target.pdb. These PDB files contain DNA structures.

The error message I encounter is as follows:
[lightdock] INFO: Loading scoring function...
[lightdock] INFO: Using DNA scoring function
[lightdock] ERROR: Error found in selected scoring function:
[lightdock] ERROR: [NotSupportedInScoringError] Residue A.C.1 or atom O5' not supported. DNA scoring only supports AMBER94 types.
It seems that the error is related to the residue named "A.C.1" and the atom "O5'" in the DNA structures. The error suggests that the DNA scoring function only supports AMBER94 types. The PDB files seem to be properly formatted and contain valid DNA structures. However, it appears that the DNA scoring function used by lightdock3.py is

![e1](https://github.com/lightdock/lightdock/assets/135914776/2d697ee4-472a-40ab-a7ea-4210498b0def)
![e2](https://github.com/lightdock/lightdock/assets/135914776/be8ace5a-5d36-4654-9005-1a8d316fab77)
 not compatible with these specific residues or atoms.
I would appreciate any assistance in resolving this issue or any suggestions for alternative approaches to perform DNA-DNA docking using the LightDock software.
Feel free to add any additional information or details that you think might be relevant in helping to address the issue.

**Comment by alchemistcai** [comment]
Clear the tmpfiles generated by `lightdock3_setup.py` and try this conversion for AMBER94 atom type compatibility by conda and Ambertools:

> [install ambertools](https://ambermd.org/GetAmber.php#ambertools)
> [convert atom types](https://ambermd.org/tutorials/basic/tutorial9/index.php)

```bash
conda install -c conda-forge ambertools
pdb4amber --reduce xxx.pdb > xxx.amber.pdb
```

Then use `lightdock3_setup.py` again.

See also #45 ,a similar problem.

**Comment by brianjimenez** [comment]
Closing issue since there is no feedback. Please feel free to reopen if needed.
