### ISSUE TITLE
Freezes after a while

### ISSUE THREAD

**Issue by stianale** [lightdock/lightdock#62]
My protein-DNA docking analyses freeze/timeout after just under 400 swarms every time. I am following the protein-DNA docking tutorial.

**Comment by brianjimenez** [comment]
Please, could you describe in more detail what is your actual workflow, OS, version of LightDock, input structures..?

**Comment by stianale** [comment]
**Sorry, of course. OS is Ubuntu 22.04. I have a pdb file for DNA generated from 3D-Dart (consists of chains A and B) and a protein from AlphaFold2. I use a restraints.list. Here is part of the final lightdock_protein.pdb:**

ATOM      1  N   TYR A  33     -19.338  -2.079  12.345  1.00 89.44           N
ATOM      2  CA  TYR A  33     -19.806  -1.688  11.017  1.00 89.44           C
ATOM      3  C   TYR A  33     -18.947  -0.554  10.458  1.00 89.44           C
ATOM      4  O   TYR A  33     -18.556  -0.584   9.286  1.00 89.44           O
ATOM      5  CB  TYR A  33     -21.275  -1.262  11.064  1.00 89.44           C
ATOM      6  CG  TYR A  33     -21.838  -0.887   9.712  1.00 89.44           C

**And here is part of the final lightdock_dna.pdb:**

ATOM      1  P    DC A   1       0.564   8.277 -26.794  1.00  0.00           P
ATOM      2  O1P  DC A   1       0.592   9.612 -27.432  1.00  0.00           O
ATOM      3  O2P  DC A   1       1.424   8.109 -25.601  1.00  0.00           O
ATOM      4  O5'  DC A   1      -0.944   7.888 -26.428  1.00  0.00           O
ATOM      6  C5'  DC A   1      -1.766   7.259 -27.430  1.00  0.00           C 

**Everything up and including the setup step works in regular lightdock 0.9.4, so I downloaded lightdock-rust and moved these temporary results over there and wrote a korn shell script. However, I don't seem to get any models generated when running ant_thony.py:**

# Before these commands, I I had to run these out-commented commands first

# Convert ANM data
#lgd_flatten.py lightdock_rec.nm.npy rec_nm.npy
#lgd_flatten.py lightdock_lig.nm.npy lig_nm.npy

ls *.dat | sed "s/initial_positions_/swarm_/g" | sed "s/.dat//g" > swarmlist.txt

swarmlist1=$(cat swarmlist.txt)

for swarm in $swarmlist1;
do
mkdir "${swarm}"
done

sed -i '1!s/^/..\//g' swarmlist.txt

for swarm in $swarmlist1;
do
cd "${swarm}"
cp -r ../data ../setup.json ../restraints.list ../rec_nm.npy ../lig_nm.npy ../lightdock_* ../dna.pdb .
cd ..
done

sed "s/swarm_/initial_positions_/g" swarmlist.txt | sed "s/$/.dat/g" > initial_list.txt

paste swarmlist.txt initial_list.txt > swarmlist_final.txt

sed -i "s/initial_positions_0.dat/..\/initial_positions_0.dat/g" swarmlist_final.txt

while IFS="$(printf '\t')" read -r swarm initial;
do
cd "${swarm}"
../../../target/release/lightdock-rust setup.json "${initial}" 100 dna
done < swarmlist_final.txt

...

**The rest of the script is the exact part that comes after the simulation in the tutorial on protein-DNA docking online**

**Comment by brianjimenez** [comment]
Did the simulation run? If `gso_100.out` files are generated, it might be a problem a problem with generate conformations script or the clustering.

**Comment by stianale** [comment]
It worked when I changed my script and used the execution.sh script located in one of the example folders as a blueprint instead.

**Comment by brianjimenez** [comment]
Then it looks like something related to your custom script. Difficult for me to the debug, see if there is any error or warning on the output.

**Comment by brianjimenez** [comment]
Closing for now, feel free to reopen it if you need further assistance.
