### ISSUE TITLE
Support for non standard amino acids

### ISSUE THREAD

**Issue by amin-sagar** [lightdock/lightdock#64]
Hello.
Thanks for this awesome work.

I am wondering if there is a way to use non-standard amino acids with lightdock. 
I am looking at methylated side chains right now, but I am trying to understand if there is a standard way to add support for more radical modifications.
I would be really grateful for any suggestions.

Best,
Amin,

**Comment by alchemistcai** [comment]
The framework of  lightdock supports non-standard amino acids in theory.

It needs scoring functions designed for non-standard residues and structure recognization for them,though.

I suggest [haddock](https://wenmr.science.uu.nl/haddock2.4/) if you urgently need non-standard amino acid support in protein-protein/peptide/ligand docking works.

Here are some [non-standard residues it supports now](https://wenmr.science.uu.nl/haddock2.4/library).

Here is [a tutorial of haddock](https://www.bonvinlab.org/education/HADDOCK24/HADDOCK24-local-tutorial/),which alters a  histidine into a phosphorylated histidine.

By the way,haddock utilizes an computational engine called [CNS](http://cns-online.org/v1.3/) to treat non-standard structures.If you need more radical modifications that are out of support lists,you can ask haddock's community for help.

Rosetta,as a powerful suit for protein designments,may also support this.However,I haven't use Rosetta before,I can't give more detailed information.

Hope this helps you.

**Comment by brianjimenez** [comment]
To add on top of @alchemistcai 's response, you can always manually add new atom types and residues to some of the supported scoring functions without re-parametrizing. A good example is in the `cpydock` scoring function where the AMBER94 force-field is internally used and it is possible to easily add or modify types on the Python files:
- https://github.com/lightdock/lightdock/blob/master/lightdock/scoring/cpydock/data/amber.py
- https://github.com/lightdock/lightdock/blob/master/lightdock/scoring/cpydock/data/solvation.py
- https://github.com/lightdock/lightdock/blob/master/lightdock/scoring/cpydock/data/vdw.py
