### ISSUE TITLE
Ligands are not placed in designated swarm centers

### ISSUE THREAD

**Issue by spoudel1** [lightdock/lightdock#65]
Perhaps I am missing something so might not be a bug. 
I am manually deciding at which swarm centers (obtained from swarm_centers.pdb file) i want to dock my ligand. Except for swarm 0 and sometimes 1, none of the ligands are placed in the right swarm_center coordinates. for example (see below), I want my ligand (cyan color) to be placed in the swarm_2  - as the number start from 0 (represented as gray sphere) but as you can see the ligands are placed in completely different place. I am using your example protein-ligand i.e. 2UUY as an example. 

![image](https://github.com/lightdock/lightdock/assets/9662974/25711742-9b33-430f-b65e-9ba0775bb564)

**Comment by JorgeRoel** [comment]
Hi @spoudel1 

In LightDock, swarms have a radius of 10Å (https://github.com/lightdock/lightdock/blob/master/lightdock/constants.py) and the center of the ligand is always placed within this distance from the swarm center (your gray sphere). For visualization purposes, we use H atoms as swarm centers in swarm_centers.pdb file (If i'm not mistaken). Otherwise, if you don't assign an atom type they won't show up in PyMOL. So basically what you are seeing here is approximately a swarm center of 1.2Å so the real swarm is ~10x larger your gray sphere. You can adjust in PyMOL the radius with the alter command and your green molecule will be embedded within its corresponding swarm.

**Comment by JorgeRoel** [comment]
P.S: You should be looking at the poses generated using gso_0.out (i.e. at step 0: prior the simulation)

**Comment by spoudel1** [comment]
I see. But the ligand is still very far. I did look into the pdb generated from gso_0.out and the closest res from the center of the swarm is 30A away. Is there a max distance that is also set? I saw in the tutorial that max_vision range is 40A, is that the reason why the ligand is that far? Thank you for helping me understand this.

**Comment by brianjimenez** [comment]
Hi @spoudel1 , I don't think you're looking to the correct structures.

Running setup with `-sp`, LightDock will generate `.bild` files which contains the representations of the initial poses as 3D-axis, compatible with Chimera and ChimeraX.

I'm using the latest version on main (`lgd_setup.py`), but same applies to previous versions (`lightdock3_setup.py`):

```bash
lgd_setup.py 2UUY_rec.pdb 2UUY_lig.pdb --noxt --noh --now -sp
[lgd_setup] INFO: Ignoring OXT atoms
[lgd_setup] INFO: Ignoring Hydrogen atoms
[lgd_setup] INFO: Ignoring water
[lgd_setup] INFO: Reading structure from 2UUY_rec.pdb PDB file...
[lgd_setup] INFO: 1628 atoms, 223 residues read.
[lgd_setup] INFO: Ignoring OXT atoms
[lgd_setup] INFO: Ignoring Hydrogen atoms
[lgd_setup] INFO: Ignoring water
[lgd_setup] INFO: Reading structure from 2UUY_lig.pdb PDB file...
[lgd_setup] INFO: 415 atoms, 55 residues read.
[lgd_setup] INFO: Calculating reference points for receptor 2UUY_rec.pdb...
[lgd_setup] INFO: Reference points for receptor found, skipping
[lgd_setup] INFO: Done.
[lgd_setup] INFO: Calculating reference points for ligand 2UUY_lig.pdb...
[lgd_setup] INFO: Reference points for ligand found, skipping
[lgd_setup] INFO: Done.
[lgd_setup] INFO: Saving processed structure to PDB file...
[lgd_setup] INFO: Done.
[lgd_setup] INFO: Saving processed structure to PDB file...
[lgd_setup] INFO: Done.
[lgd_setup] INFO: Calculating starting positions...
[lgd_setup] INFO:   * Surface density: TotalSASA/50.00
[lgd_setup] INFO:   * Swarm radius: 10.00 Å
[lgd_setup] INFO:   * 180° flip of 50% of starting poses: False
[lgd_setup] INFO:   * Ligand Max Diameter: 39.05 Å
[lgd_setup] INFO:   * Surface distance: 9.76 Å
[lgd_setup] INFO: Swarms after incompatible filter: 911
[lgd_setup] INFO: Swarms after interior points filter: 911
[lgd_setup] INFO: Generated 182 positions files
[lgd_setup] INFO: Done.
[lgd_setup] INFO: Number of calculated swarms is 182
[lgd_setup] INFO: Preparing environment
[lgd_setup] INFO: Done.
[lgd_setup] INFO: LightDock setup OK
```

Then open the parsed receptor, swarm centers and first swarm bild file with ChimeraX:

```bash
chimerax lightdock_2UUY_rec.pdb init/swarm_centers.pdb init/starting_poses_0.bild
```

I've selected first swarm, which is `SWR` residue and residue number 1 and colored it in magenta (`select #2:1`):

![2uuy](https://github.com/lightdock/lightdock/assets/4330278/2cabff1c-4048-4b04-8725-ef2742a6d4da)

As seen in this picture, models are randomly placed around the swarm center, in a sphere of 10A radius. I've also depicted an estimated distance from the swarm center to the closest atom:

![image1](https://github.com/lightdock/lightdock/assets/4330278/bd0a51b5-071d-45a7-a7df-37d7c4b58b0f)

![image2](https://github.com/lightdock/lightdock/assets/4330278/d85240bc-3ba4-41a6-be07-d1c9e6e22ef9)

**Comment by spoudel1** [comment]
Hi Brian, Thank you for running the test run. This makes sense and starting positions are all correct. I was looking at the result in the specific swarm folders. In this example with 2UUY, the script finds a total of 182 swarm centers so it generates 182 swarm folders outside the init folder. If i look at the first swarm (i.e., swarm_0), all the pdb files with ligands (generated using the script lgd_generate_conformations.py) are placed within the 10A radius of the swarm center. But when i looked at other swarms say swarm_10, ligands were not near any of these glowcenters. My understanding was these ligands should not go beyond these glowcenters or swarm center radius of 10A? But since you take neighboring swarms into consideration i guess their radius also gets added as a space to explore, is that why these ligands are very far from the original swarm center?

**Comment by JorgeRoel** [comment]
Hi @spoudel1 

Please have a look a the following movie about what happens inside a swarm: https://www.youtube.com/watch?v=HaA5Y1AkoVM&ab_channel=JorgeRoel

As you can see, the glowworms (ligands) represented by a 3d-axis start evenly distributed inside the swarm (10Å radius sphere). As the simulation progresses, they optimized towards the best pose within their vision range. The optimization is only intra-swarm.

As for more general terms, one thing is the swarm center (a 3d point in space) and other thing is the swarm (a 3d sphere) defined by a 10Å radius.
