### ISSUE TITLE
Performance for protein-DNA docking

### ISSUE THREAD

**Issue by stianale** [lightdock/lightdock#66]
Has there been done research into the accuracy of Lightdock for protein-DNA docking compared to ie. HADDOCK, RosETTAFold2NA, etc.? I have found comparisons regarding protein-protein docking, but not protein-DNA. Also, what are the pros and cons of the Lightdock alghorithm compared to other softwares?

**Comment by brianjimenez** [comment]
Hi @stianale, we did some internal tests and the results were really good, including protein-DNA and aptamer docking. We did not benchmark the LightDock performance extensively and we did not compare it with other methods.

Let me know if you need any help from the LightDock perspective if you plan to benchmark different methods.

**Comment by dberma15** [comment]
Do you have any demo examples for DNA binding? I'm not having any luck with finding an implementing anything. The one example I found, [here](https://lightdock.org/tutorials/0.9.1/dna_docking), does not work as I'm not able to get 3.1. Protein working. Reduce and pdb_atom_renumber do not execute.

**Comment by alchemistcai** [comment]
Do Reduce and pdb_atom_renumber give some output infomation? I tested the tutorials before and successed. @dberma15

**Comment by dberma15** [comment]
> Do Reduce and pdb_atom_renumber give some output infomation? I tested the tutorials before and successed. [@dberma15](https://github.com/dberma15)

I tried installing them and they don't seem to work. 
I typically get a response like this when I try to install from conda using `conda install -c cctbx cctbx_monomer_library `, `pip install pdb-tools`, and  `conda install reduce -c bioconda`: 
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cctbx_monomer_library

Current channels:

  - https://conda.anaconda.org/cctbx/linux-64
  - https://conda.anaconda.org/cctbx/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```
