### ISSUE TITLE
Use MPI for simulation

### ISSUE THREAD

**Issue by zhangjuan233** [lightdock/lightdock#67]
Hello, the '-mpi' flag was used when executing the lightdock3.py file. However, during the run, when executing comm.Barrier(), and num_workers = comm.size, the variable num_workers is assigned the value of 1. This results in an error in the file "lightdock-master/lightdock/simulation/docking_mpi.py", specifically at line 226 in the run_simulation function:starting_points_files[id_swarm],The error message is "IndexError: list index out of range." Is this due to a possible incorrect installation of mpi4py?
![error](https://github.com/lightdock/lightdock/assets/129643154/6da36c3b-b31d-43bb-923c-8d5264611d49)

**Comment by brianjimenez** [comment]
Line 226 corresponds to `parser.args.translation_step`. Please could you share your setup.json file and the command line prompt used to run setup?

**Comment by zhangjuan233** [comment]
> Line 226 corresponds to `parser.args.translation_step`. Please could you share your setup.json file and the command line prompt used to run setup?     
Thank you for your reminder. The error issue has been resolved. Regarding the previously mentioned problem of num_workers being set to 1, it was because mpi4py was not installed correctly on the server where I am running the code, wasn't it?

**Comment by zhangjuan233** [comment]
> Line 226 corresponds to `parser.args.translation_step`. Please could you share your setup.json file and the command line prompt used to run setup?

Thank you for your reminder. The error issue has been resolved. Regarding the previously mentioned problem of num_workers being set to 1, it was because mpi4py was not installed correctly on the server where I am running the code, wasn't it?

**Comment by brianjimenez** [comment]
I guess there was some specific `mpi4py` issue in your local installation. `mpirun -n NUM_PROCESSES lgd_run.py setup.json 100` should do the trick.
