### ISSUE TITLE
Protein-RNA docking

### ISSUE THREAD

**Issue by aminijavad** [lightdock/lightdock#72]
Hi, I am trying to verify the interaction of a circular RNA (in a circular form, not linear form) with a protein by Lightdock3. All steps were performed properly until the setup step. In this step, I faced this error:

TypeError: can't multiply sequence by non-int of type 'Forward'

![Screenshot from 2024-03-09 15-02-22](https://github.com/lightdock/lightdock/assets/37981091/04a2af04-ce59-467f-89af-68249d382bfd)

I will appreciate if you help me to solve this problem.

**Comment by JorgeRoel** [comment]
Hi @aminijavad 

Thanks for your message. This error originates from ProDy not selecting your RNA molecule for ANM calculations (flexibility). See line 42 in lightdock/structure/nm.py How do your ATOM records in your rna.pdb look like? My guess is that there is a mismatch between the way RNA bases are defined in your PDB and the way ProDy understands them. Also, please have a look at this tutorial: https://lightdock.org/tutorials/0.9.3/rna_docking#22-rna (if you haven't done so) since some preprocessing steps are needed for protein-RNA docking

**Comment by aminijavad** [comment]
Hi Jorge

Thank you for your response. I tried to proceed according to the tutorial,
but I don't know which part I did wrong. Sorry, but I don't know the proper
structure for ProDy, do you mind if explain it more and how I can solve
this problem?

I also sent you the RNA's PDB file, if you wish to glance at it.

I appreciate your time and consideration

**Comment by JorgeRoel** [comment]
hi @aminijavad 

Where did you send me the pdb file? I can't find it

**Comment by aminijavad** [comment]
Oh sorry, I answered you from my email, not GitHub. Here you are 

https://filebin.net/q4r1wy2whhb2q3o8

**Comment by JorgeRoel** [comment]
Could you please send it **uncompressed** to jrg.roel@gmail.com?

**Comment by aminijavad** [comment]
sure

**Comment by JorgeRoel** [comment]
Hi @aminijavad Sorry for the mistake as I wrongly read the error from your screenshot. The problem originates from your protein.pdb file instead. I verified your circ.pdb and there's no issue about it. Could you please share that pdb with me together with the exact command (lightdock3_setup.py) you are running? Attached screenshot of successful setup with your rna but with a different protein.

![Screenshot 2024-03-11 at 13 18 22](https://github.com/lightdock/lightdock/assets/11388565/24604f79-8a57-48ca-9ee5-0445b34859fd)

**Comment by aminijavad** [comment]
Hi Jorge
Sure
I appreciate your help. I'll send it to your email. I ran these commands:

reduce -Trim A1_protein.pdb > 1A1T_A_noh.pdb
reduce -BUILD 1A1T_A_noh.pdb > 1A1T_A_h.pdb

pdb_reatom 1A1T_A_h.pdb > protein.pdb

lightdock3_setup.py protein.pdb rna.pdb -anm

**Comment by aminijavad** [comment]
Here you are

**Comment by JorgeRoel** [comment]
Thanks @aminijavad I have no issues doing the setup. See screenshot:
![Screenshot 2024-03-11 at 14 11 18](https://github.com/lightdock/lightdock/assets/11388565/fc054310-0dfa-4f88-a5a1-e6bc302ca608)

My guess is that your protein.pdb file is empty as pdb_reatom takes as an argument a number to renumber from:

pdb_reatom.py number pdb file

Could you please check?

**Comment by aminijavad** [comment]
I'm wondering why your run performed without any error! 
No, it wasn't.

**Comment by aminijavad** [comment]
could you please share your commands?

**Comment by JorgeRoel** [comment]
You can see them on the top of the screenshot:

lightdock3_setup.py A1_protein.pdb circ.pdb -anm

**Comment by aminijavad** [comment]
Sorry to bother you, but is it possible to see your previous commands?

**Comment by JorgeRoel** [comment]
There's nothing else. Just took the 2 pdb files you sent me and ran the setup

**Comment by aminijavad** [comment]
I'm really confused, I still getting the error!

**Comment by alchemistcai** [comment]
I tried it and the setup works fine.

Try to update pyparsing since `enablePackrat` is a new method in version 3.0 and  prody and lightdock don't specify the version of pyparsing in their requirements.

I hope this works @aminijavad

**Comment by brianjimenez** [comment]
Only to add to the discussion that `pyparsing` is not a LightDock dependency, but ProDy's.

@aminijavad if you try disabling RNA ligand flexibility with `-anm -ar 10 -al 0` that would work and bypass the ProDy issue.

**Comment by JorgeRoel** [comment]
We close this for now as the error could not be replicated in tow different settings

**Comment by aminijavad** [comment]
> I tried it and the setup works fine.
> 
> Try to update pyparsing since `enablePackrat` is a new method in version 3.0 and prody and lightdock don't specify the version of pyparsing in their requirements.
> 
> I hope this works @aminijavad

I will do it thank you

**Comment by aminijavad** [comment]
> We close this for now as the error could not be replicated in tow different settings

Thank you for your time Jorge

**Comment by aminijavad** [comment]
> Only to add to the discussion that `pyparsing` is not a LightDock dependency, but ProDy's.
> 
> @aminijavad if you try disabling RNA ligand flexibility with `-anm -ar 10 -al 0` that would work and bypass the ProDy issue.

Sure, thank you
