### ISSUE TITLE
Where is lightdock3_setup.py script generated?

### ISSUE THREAD

**Issue by wjs20** [lightdock/lightdock#78]
Hi 

Not really a bug, just a (maybe stupid) question, but I am trying to understand how lightdock works a little better, and I can't figure out where the lightdock3_setup.py executable is generated. I can't find it in the source, so I assume it must be generated, or another file must be renamed to lightdock3_setup.py. Can you explain how this works?

Thanks

**Comment by alchemistcai** [comment]
In the `bin` folder.

After installed by pip,it will locate in that python environment's `bin` folder.

Use `whereis lightdock3_setup.py` for its abspath.

**Comment by wjs20** [comment]
When I pip install from pypi, I can find the lightdock3_setup.py file in the bin/ of my virtualenv. What I can't figure out is where this file comes from. There is no lightdock3_setup.py in the source code. There is an "lgd_setup.py" file, but no "lightdock3_setup.py" file, so I am assuming this is generated at some point during the setup, but I can't figure out where. If I clone the repo and `pip install -e .` the lightdock3_setup.py file is not created in the virtualenvs bin/

Thanks for your help!

**Comment by alchemistcai** [comment]
oh, `lightdock3.py` is renamed to `lgd_run.py` and `lightdock3_setup.py` is renamed to `lgd_setup.py`  from  version 0.9.4 to  1.0.0.

Version 1.0.0 is under development,not ready for public distribution.

Use `pip install lightdock` is the recommend way.

You can use `lgd_setup.py` and `lgd_run.py` if you install from the souce,though.

**Comment by wjs20** [comment]
Ahh I see. Thanks for clarifying.
