### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by javierabaeza** [lightdock/lightdock#84]
I installed Lightdock version 0.9.4. I am trying to launch a calculation using restraints and membrane. I had the problems noted in #76 and #81 and solved them as instructed. I launched again and now I get this error:

lightdock3_setup.py REC.pdb SURF4_fix.pdb --noxt --noh -membrane -r restraints.txt

(...)
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.731
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.732
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.733
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.734
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.735
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.736
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.737
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.738
[lightdock3_setup] INFO: 25170 atoms, 3822 residues read.
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Reading structure from SURF4_fix.pdb PDB file...
[lightdock3_setup] INFO: 2152 atoms, 272 residues read.
[lightdock3_setup] INFO: Calculating reference points for receptor REC.pdb...
[lightdock3_setup] INFO: Reference points for receptor found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating reference points for ligand SURF4_fix.pdb...
[lightdock3_setup] INFO: Reference points for ligand found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Reading restraints from restraints.txt
[lightdock3_setup] INFO: Number of receptor restraints is: 0 (active), 5 (passive)
[lightdock3_setup] INFO: Number of ligand restraints is: 0 (active), 0 (passive)
[lightdock3_setup] INFO: Calculating starting positions...
[lightdock3_setup] INFO:   * Surface density: TotalSASA/50.00
[lightdock3_setup] INFO:   * Swarm radius: 10.00 Å
[lightdock3_setup] INFO:   * 180° flip of 50% of starting poses: False
[lightdock3_setup] INFO:   * Ligand Max Diameter: 78.61 Å
[lightdock3_setup] INFO:   * Surface distance: 19.65 Å
[lightdock3_setup] INFO: Swarms after incompatible filter: 241
[lightdock3_setup] INFO: Swarms after interior points filter: 216
[lightdock3_setup] INFO: Swarms after occlusion filter: 216
/home/oc/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/oc/.local/lib/python3.10/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/oc/.local/bin/lightdock3_setup.py", line 142, in <module>
    starting_points_files = calculate_starting_positions(
  File "/home/oc/.local/lib/python3.10/site-packages/lightdock/prep/simulation.py", line 191, in calculate_starting_positions
    starting_points_files = calculate_initial_poses(
  File "/home/oc/.local/lib/python3.10/site-packages/lightdock/prep/poses.py", line 523, in calculate_initial_poses
    swarm_centers = apply_membrane(
  File "/home/oc/.local/lib/python3.10/site-packages/lightdock/prep/poses.py", line 436, in apply_membrane
    min_z = max(layer) + translation[2]
**ValueError: max() arg is an empty sequence.**

I use Ubuntu 22.04
.

**Comment by brianjimenez** [comment]
From this warning `[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MB.731` it seems like the membrane beads are identified by `MB` and not by `MMB`. Could you please try renaming them, removing all files except the input and rerun the setup?

**Comment by javierabaeza** [comment]
I solved the error by adding one more space in each column before the MMB, it seems that the identation of the prepare4lightdock.py script is not correct at that point.

**Comment by brianjimenez** [comment]
Thanks for the feedback @javierabaeza. Will have a look at the script and fix it if needed.
