### ISSUE TITLE
Problem with lightdock3_setup.py 

### ISSUE THREAD

**Issue by javierabaeza** [lightdock/lightdock#85]
I am docking using the membrane and restraint modules. I am taking as references amino acids that are in the extracellular part. However, when I run lightdock3_setup the swarms folders are not generated. 

R A.ASP.562 P
R A.THR.563 P
R A.LEU.564 P
R A.LYS.565 P
R A.ASP.566 P
R A.LEU.567 P
R A.THR.568 P
R A.LYS.569 P
R A.ASN.575 P

This is the restraints file I'm using (I've tried removing and adding amino acids and also playing with whether they are passive or active)
lightdock3_setup.py --noxt --noh --membrane -flip -rst restraints.txt REC.pdb LIG_fix.pdb (I use flip if the program made the folders but not work)
The output I get:
![imagen](https://github.com/lightdock/lightdock/assets/111246782/37310a0a-7ab0-4015-a263-9d3a8e20b034)

I use Ubuntu 22.04 and the lightdock version available in PIP

**Comment by brianjimenez** [comment]
It is possible that the swarms are being generated on the wrong interface and then filtering using restraints has a result of 0 swarms. What if you try using the structure from the tutorial and applying a couple of restraints (https://lightdock.org/tutorials/0.9.3/membrane), does it happen the same? If the structures are not confidential, I can have a look myself.

**Comment by javierabaeza** [comment]
I used the tutorial files and it generates the files. I don't understand why in the system I have it doesn't generate them. I upload the files to see what the problem could be.



Thank you very much.

**Comment by brianjimenez** [comment]
Hi @javierabaeza , sorry for the delay. Here it is the receptor structure oriented in the proper way to avoid your issue.

![swarms](https://github.com/lightdock/lightdock/assets/4330278/3ab55724-c7ad-49f2-bb0f-55d16e0806e4)

What I did was basically rotating the structure on PyMol with the command `rotate y, 180, all`, and then saving it as a new PDB (attached).

Now the swarms are correctly placed over your restraints.

[REC_rotated.pdb.zip](https://github.com/user-attachments/files/15925154/REC_rotated.pdb.zip)

The LightDock setup command I used is:

```bash
(venv)$ lightdock3_setup.py REC_rotated.pdb LIG.pdb --noxt --now --noh --membrane -rst restraints.txt 
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Ignoring water
[lightdock3_setup] INFO: Reading structure from REC_rotated.pdb PDB file...
[lightdock3_setup] INFO: 25170 atoms, 3822 residues read.
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Ignoring water
[lightdock3_setup] INFO: Reading structure from LIG.pdb PDB file...
[lightdock3_setup] INFO: 2152 atoms, 272 residues read.
[lightdock3_setup] INFO: Calculating reference points for receptor REC_rotated.pdb...
[lightdock3_setup] INFO: Reference points for receptor found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating reference points for ligand LIG.pdb...
[lightdock3_setup] INFO: Reference points for ligand found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Reading restraints from restraints.txt
[lightdock3_setup] INFO: Number of receptor restraints is: 0 (active), 9 (passive)
[lightdock3_setup] INFO: Number of ligand restraints is: 0 (active), 0 (passive)
[lightdock3_setup] INFO: Calculating starting positions...
[lightdock3_setup] INFO:   * Surface density: TotalSASA/50.00
[lightdock3_setup] INFO:   * Swarm radius: 10.00 Å
[lightdock3_setup] INFO:   * 180° flip of 50% of starting poses: False
[lightdock3_setup] INFO:   * Ligand Max Diameter: 78.61 Å
[lightdock3_setup] INFO:   * Surface distance: 19.65 Å
[lightdock3_setup] INFO: Swarms after incompatible filter: 266
[lightdock3_setup] INFO: Swarms after interior points filter: 242
[lightdock3_setup] INFO: Swarms after occlusion filter: 242
[lightdock3_setup] INFO: Generated 108 positions files
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Number of calculated swarms is 108
[lightdock3_setup] INFO: Preparing environment
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: LightDock setup OK
```

**Comment by javierabaeza** [comment]
@brianjimenez Thank you very much! I was finally able to launch the calculation without any problems.
