### ISSUE TITLE
ERROR: Number of atoms in ProDy (5957) vs LightDock (5963)

### ISSUE THREAD

**Issue by BirupakshaDas** [lightdock/lightdock#86]
![Screenshot from 2024-06-15 16-17-10](https://github.com/lightdock/lightdock/assets/120272447/f5155ae7-e714-439e-aad3-fa3e8bb5b4da)

Kindly suggest me how to resolve the issue.... Thanks in advance...

**Comment by brianjimenez** [comment]
Try rebuilding missing atoms on backbone and side chains and rerun setup again (ProDy library for calculating ANM requires of this).

**Comment by BirupakshaDas** [comment]
Unfortunately, even after building missing residues, i get the same error

**Comment by brianjimenez** [comment]
With very same numbers? If there are hydrogen atoms, remove all of them and also remove cofactors, ions, waters and everything starting with `HETATM` in the pdb input structures.

**Comment by JorgeRoel** [comment]
How many THR19 you have in your 5jhm_rec.pdb? Looks like you have it duplicated and missing the 3 heavy side atoms (CB,OG1,OG2) * 2 = 6, which is what prody is telling you 5957-5963 = -6 atoms

**Comment by BirupakshaDas** [comment]
![Screenshot 2024-06-17 at 3 51 02 PM](https://github.com/lightdock/lightdock/assets/120272447/2234b8ce-72e7-4cf4-aa81-2a93217fe441)


This is the data you were mentioning. I could not find the issue. Can you look for it in the picture? Thanks in advance.

**Comment by JorgeRoel** [comment]
Can you share the PDBs? I also see that your hs_lig.pdb has only 1 residue?

**Comment by BirupakshaDas** [comment]
Yes, my ligand is a heparan sulphate disaccharide (ZINC id. 85551958) , which is a Glycosaminoglycan. I now realise that the ligand is not a protein, but i think that is not the main issue?

**Comment by JorgeRoel** [comment]
This is indeed not the issue prody is complaining about but your ligand will not work within LightDock. I advise you to try HADDOCK instead
