### ISSUE TITLE
errors when running lightdock3_setup.py

### ISSUE THREAD

**Issue by Luckken21** [lightdock/lightdock#88]
./lightdock3_setup.py ../Files/cdc42A.pdb ../Files/cdc42B.pdb --noxt --noh --now --anm
[lgd_setup] INFO: Ignoring OXT atoms
[lgd_setup] INFO: Ignoring Hydrogen atoms
[lgd_setup] INFO: Ignoring water
[lgd_setup] INFO: Reading structure from ../Files/cdc42A.pdb PDB file...
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue GDP.198
[pdb] WARNING: Possible problem: [ResidueNonStandardError] Can not check non-standard residue MG.199
[lgd_setup] INFO: 1522 atoms, 193 residues read.
[lgd_setup] INFO: Ignoring OXT atoms
[lgd_setup] INFO: Ignoring Hydrogen atoms
[lgd_setup] INFO: Ignoring water
[lgd_setup] INFO: Reading structure from ../Files/cdc42B.pdb PDB file...
[pdb] WARNING: Possible problem: [SideChainError] Incomplete sidechain for residue LEU.260
[lgd_setup] INFO: 1586 atoms, 197 residues read.
[lightdock3_setup] INFO: Calculating reference points for receptor ../Files/cdc42A.pdb...
[lightdock3_setup] INFO: Reference points for receptor found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating reference points for ligand ../Files/cdc42B.pdb...
[lightdock3_setup] INFO: Reference points for ligand found, skipping
[lightdock3_setup] INFO: Done.
[lgd_setup] INFO: Saving processed structure to PDB file...
[lgd_setup] INFO: Done.
[lgd_setup] INFO: Saving processed structure to PDB file...
[lgd_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating ANM for receptor molecule...
Traceback (most recent call last):
  File "/gpfs/share/home/2200012187/lightdock1/lightdock-0.9.4/bin/./lightdock3_setup.py", line 93, in <module>
    calculate_anm(receptor, args.anm_rec, args.anm_rec_rmsd, args.anm_seed, DEFAULT_REC_NM_FILE)
  File "/gpfs/share/home/2200012187/lightdock/lightdock/lightdock/prep/simulation.py", line 136, in calculate_anm
    modes = calculate_nmodes(parsed_lightdock_structure, num_nmodes, rmsd, seed, structure)
  File "/gpfs/share/home/2200012187/lightdock/lightdock/lightdock/structure/nm.py", line 44, in calculate_nmodes
    molecule_anm.calcModes(n_modes=n_modes)
  File "/gpfs/share/home/2200012187/mambaforge/envs/lightdock/lib/python3.10/site-packages/prody/dynamics/anm.py", line 218, in calcModes
    values, vectors, vars = solveEig(self._hessian, n_modes=n_modes, zeros=zeros, 
  File "/gpfs/share/home/2200012187/mambaforge/envs/lightdock/lib/python3.10/site-packages/prody/utilities/eigtools.py", line 88, in solveEig
    values, vectors = _eigh(M, eigvals, turbo)
  File "/gpfs/share/home/2200012187/mambaforge/envs/lightdock/lib/python3.10/site-packages/prody/utilities/eigtools.py", line 41, in _eigh
    values, vectors = linalg.eigh(M, turbo=turbo, eigvals=eigvals)
TypeError: eigh() got an unexpected keyword argument 'turbo'
I meet this problem but I cannot solve it. Thanks a lot if you can help me.

**Comment by alchemistcai** [comment]
> The `turbo` and `eigvals` arguments from `scipy.linalg.{eigh,eigvalsh}` have been removed.
> Since scipy 1.14.0
> https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html

Try to install scipy<=1.13.1 or reinstall prody.This is required by prody. @Luckken21

**Comment by Luckken21** [comment]
Thanks! I solve it now, but I meet with another problem. Could you please help me? [ANM] ERROR: Number of atoms in ProDy (1521) vs LightDock (1493)
[lightdock3_setup] ERROR: LightDock setup failed. Please see:
[lightdock3_setup] ERROR: [NormalModesCalculationError] Number of atoms is different

**Comment by Luckken21** [comment]
And I have used pdbfixer according to previous issues

**Comment by alchemistcai** [comment]
According to the log,it seems like that `cdc4A.pdb` has non-standard residue `GDP.198` and `MG.199`;`cdc4B.pdb` has  incomplete atoms in `LEU.260`.

Maybe turning `GDP.198` and `MG.199` from `ATOM` to `HETATM` records in the pdb file helps.

Also,`cdc4B.pdb` needs pdbfixer,too. @Luckken21

**Comment by Luckken21** [comment]
OK，I solve the problems successfullly! Thank you very much!

**Comment by Luckken21** [comment]
OK，I solve the problems successfullly! Thank you very much!
