### ISSUE TITLE
Accept lowercase for chain IDs 

### ISSUE THREAD

**Issue by alexandrefassio** [lightdock/lightdock#89]
Hi there, 

It seems Lightdock cannot handle chains whose ID is in lowercase:

https://github.com/lightdock/lightdock/blob/4654ee58542e99174776b2f80dbcfb673e918da1/lightdock/prep/simulation.py#L344

Some PDBs have both upper and lower cases in the same file (e.g., 'A' and 'a'; see PDB [7TYV](https://www.rcsb.org/structure/7TYV)), which makes the restraints system break for these cases.

I can pre-process the files before running Lightdock, but it would be interesting to handle such cases as well.

bests

**Comment by brianjimenez** [comment]
Sorry, I did probably ignore the notification about this issue.

Will fix it on the next release, thanks for reporting this @alexandrefassio

**Comment by brianjimenez** [comment]
This has been implemented in https://github.com/lightdock/lightdock/commit/1ad9b9c3638c921659f76b9be0276f00bb965838
