### ISSUE TITLE
Missing import and incorrect function call signature in `lightdock/simulation/docking_mpi.py`

### ISSUE THREAD

**Issue by bzoracler** [lightdock/lightdock#9]
**Describe the bug**

The [`lightdock/simulation/docking_mpi.py`](https://github.com/lightdock/lightdock/blob/abed07b07ea5cf4769cfa985025efaa20655e183/lightdock/simulation/docking_mpi.py) module is:

 - Missing the `DEFAULT_LIGHTDOCK_PREFIX` import, causing `NameError` issues in lines 111 and 114;
   https://github.com/lightdock/lightdock/blob/abed07b07ea5cf4769cfa985025efaa20655e183/lightdock/simulation/docking_mpi.py#L15-L17
  https://github.com/lightdock/lightdock/blob/abed07b07ea5cf4769cfa985025efaa20655e183/lightdock/simulation/docking_mpi.py#L109-L114
 - Missing the final `anm_rec` and `anm_lig` arguments to pass to `gso = builder.create_from_file`, causing `TypeError` issues.
   https://github.com/lightdock/lightdock/blob/abed07b07ea5cf4769cfa985025efaa20655e183/lightdock/simulation/docking_mpi.py#L44-L46
  https://github.com/lightdock/lightdock/blob/abed07b07ea5cf4769cfa985025efaa20655e183/lightdock/gso/algorithm.py#L108-L111

**Expected behavior**

Changing this script to look like [`lightdock/simulation/docking_multiprocessing.py`](https://github.com/lightdock/lightdock/blob/master/lightdock/simulation/docking_multiprocessing.py) works:

https://github.com/lightdock/lightdock/blob/abed07b07ea5cf4769cfa985025efaa20655e183/lightdock/simulation/docking_multiprocessing.py#L14-L16

https://github.com/lightdock/lightdock/blob/abed07b07ea5cf4769cfa985025efaa20655e183/lightdock/simulation/docking_multiprocessing.py#L43-L46

**Comment by brianjimenez** [comment]
Fixed in 0.8.2
