### ISSUE TITLE
Trouble when selecting swarms beside CDRH3.

### ISSUE THREAD

**Issue by Thoudam-A** [lightdock/lightdock#90]
Hi, thanks for your excellent work!
When I'm working with antibody-antigen docking tasks, the model generates hundreds of swarms, but all I want to select are swarms besides CDRH3. I don't know how to select those swarms. How can I do that? I would be very grateful if you can help me!

**Comment by brianjimenez** [comment]
You may use restraints to sample only specific areas, have a look at the online tutorial: https://lightdock.org/tutorials/0.9.3/restraints

**Comment by Thoudam-A** [comment]
OK, I'll try. Thanks for your reply!

**Comment by alchemistcai** [comment]
Lightdock uses residue restraints to generate and filter swarms.

Using the most important residues on the interface as active restraints can reduce swarm amounts.
