### ISSUE TITLE
Read input PDBs from cloud storage

### ISSUE THREAD

**Issue by janhurst** [lightdock/lightdock#91]
**Is your feature request related to a problem? Please describe.**
I would like to pass input files from input cloud storage, in my specific use case Google Cloud Storage.
e.g. `lightdock3_setup.py gs://my-bucket/receptor.pdb gs://my-bucket/ligand.pdb`

**Describe the solution you'd like**
When I pass a reasonably formatted URI such as `gs://my-bucket/some.pdb` or `s3://my-s3-bucket/some.pdb` then the read function would recognize the file URI and read directly from storage.

**Describe alternatives you've considered**
Adding a wrapper/pipeline step that copies from cloud storage to local storage before calling the setup.

**Additional context**
I am implementing large scale docking experiments in a pipeline. Right now I need to copy the same inputs to local storage as a pre-step before running the lightdock steps. I imagine the lightdock steps being able to delegate the read to relevant storage backends perhaps via fsspec in much the same way tools such as Pandas does.

Writing back to cloud storage by passing say a `-out gs://my-bucket/my-experiment-results` might also be nice, it probably deserves its own feature request.

**Comment by brianjimenez** [comment]
From the point of view of the LightDock code, it should be reasonable to be implemented, but many of the libraries used by this code (thinking on ProDy, BioPython, FreeSASA) won't be prepared for having remote URI. It is tricky to take on all the corner cases and prepare temporal inputs for the libraries abovementioned. Sorry for not implementing this :(
